#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Coffin_04

#include "Basic.hpp"

#include "ABP_Coffin_04_classes.hpp"
#include "ABP_Coffin_04_parameters.hpp"


namespace SDK
{

// Function ABP_Coffin_04.ABP_Coffin_04_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_Coffin_04_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Coffin_04_C", "AnimGraph");

	Params::ABP_Coffin_04_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_Coffin_04.ABP_Coffin_04_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_4A625A0F4CDEB54DB59CF691484FC0F3
// (BlueprintEvent)

void UABP_Coffin_04_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_4A625A0F4CDEB54DB59CF691484FC0F3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Coffin_04_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_4A625A0F4CDEB54DB59CF691484FC0F3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Coffin_04.ABP_Coffin_04_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_86C5D60D4DBA421EDB6EE58AAAEB34EC
// (BlueprintEvent)

void UABP_Coffin_04_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_86C5D60D4DBA421EDB6EE58AAAEB34EC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Coffin_04_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Coffin_04_AnimGraphNode_TransitionResult_86C5D60D4DBA421EDB6EE58AAAEB34EC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Coffin_04.ABP_Coffin_04_C.ExecuteUbergraph_ABP_Coffin_04
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Coffin_04_C::ExecuteUbergraph_ABP_Coffin_04(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Coffin_04_C", "ExecuteUbergraph_ABP_Coffin_04");

	Params::ABP_Coffin_04_C_ExecuteUbergraph_ABP_Coffin_04 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

