#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MysticalGem

#include "Basic.hpp"

#include "ABP_MysticalGem_classes.hpp"
#include "ABP_MysticalGem_parameters.hpp"


namespace SDK
{

// Function ABP_MysticalGem.ABP_MysticalGem_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_MysticalGem_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MysticalGem_C", "AnimGraph");

	Params::ABP_MysticalGem_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_MysticalGem.ABP_MysticalGem_C.ExecuteUbergraph_ABP_MysticalGem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_MysticalGem_C::ExecuteUbergraph_ABP_MysticalGem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MysticalGem_C", "ExecuteUbergraph_ABP_MysticalGem");

	Params::ABP_MysticalGem_C_ExecuteUbergraph_ABP_MysticalGem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

