#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SkeletonCorpse_02

#include "Basic.hpp"

#include "ABP_SkeletonCorpse_02_classes.hpp"
#include "ABP_SkeletonCorpse_02_parameters.hpp"


namespace SDK
{

// Function ABP_SkeletonCorpse_02.ABP_SkeletonCorpse_02_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_SkeletonCorpse_02_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SkeletonCorpse_02_C", "AnimGraph");

	Params::ABP_SkeletonCorpse_02_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_SkeletonCorpse_02.ABP_SkeletonCorpse_02_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_92C4A85B4318D966CCA97D93579D4C8A
// (BlueprintEvent)

void UABP_SkeletonCorpse_02_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_92C4A85B4318D966CCA97D93579D4C8A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SkeletonCorpse_02_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_92C4A85B4318D966CCA97D93579D4C8A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SkeletonCorpse_02.ABP_SkeletonCorpse_02_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_BADE66AD43DE4A609683EB93F24C146C
// (BlueprintEvent)

void UABP_SkeletonCorpse_02_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_BADE66AD43DE4A609683EB93F24C146C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SkeletonCorpse_02_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SkeletonCorpse_02_AnimGraphNode_TransitionResult_BADE66AD43DE4A609683EB93F24C146C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SkeletonCorpse_02.ABP_SkeletonCorpse_02_C.ExecuteUbergraph_ABP_SkeletonCorpse_02
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SkeletonCorpse_02_C::ExecuteUbergraph_ABP_SkeletonCorpse_02(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SkeletonCorpse_02_C", "ExecuteUbergraph_ABP_SkeletonCorpse_02");

	Params::ABP_SkeletonCorpse_02_C_ExecuteUbergraph_ABP_SkeletonCorpse_02 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

