#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SkeletonCrossbowman

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_SkeletonCrossbowman.ABP_SkeletonCrossbowman_C.AnimBlueprintGeneratedConstantData
// 0x0187 (0x0188 - 0x0001)
struct ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_5918[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_229;                                // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_230;                               // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_231;                                // 0x0010(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_232;                                // 0x0018(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5919[0x3];                                     // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_233;                                // 0x001C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_234;                                // 0x0024(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_235;                                 // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_236;                                // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_237;                                // 0x0038(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_238;                                 // 0x0040(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_239;                                // 0x0044(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_591A[0x3];                                     // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_240;                               // 0x0048(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_241;                              // 0x004C(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_242;                               // 0x0078(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_243;                                // 0x007C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_244;                                // 0x007D(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_591B[0x2];                                     // 0x007E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_245;                                // 0x0080(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendProfile*                          __BlendProfile_246;                                // 0x0088(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_247;                                  // 0x0090(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_248;                                // 0x0098(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_249;                                // 0x0099(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_250;                                // 0x009A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_591C[0x5];                                     // 0x009B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_251;                               // 0x00A0(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_252;                                // 0x00B0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_253;                                 // 0x00B8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_254;                                // 0x00BC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_255;                                // 0x00C4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_256;                                 // 0x00CC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNodeFunctionRef                   __StructProperty_257;                              // 0x00D0(0x0020)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x00F0(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0170(0x0018)()
};
static_assert(alignof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData) == 0x000188, "Wrong size on ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_229) == 0x000004, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_229' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __FloatProperty_230) == 0x00000C, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__FloatProperty_230' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_231) == 0x000010, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_231' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __EnumProperty_232) == 0x000018, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__EnumProperty_232' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_233) == 0x00001C, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_233' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_234) == 0x000024, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_234' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __IntProperty_235) == 0x00002C, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__IntProperty_235' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_236) == 0x000030, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_236' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_237) == 0x000038, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_237' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __IntProperty_238) == 0x000040, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__IntProperty_238' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __BoolProperty_239) == 0x000044, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__BoolProperty_239' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __FloatProperty_240) == 0x000048, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__FloatProperty_240' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __StructProperty_241) == 0x00004C, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__StructProperty_241' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __FloatProperty_242) == 0x000078, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__FloatProperty_242' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __EnumProperty_243) == 0x00007C, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__EnumProperty_243' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __ByteProperty_244) == 0x00007D, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__ByteProperty_244' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_245) == 0x000080, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_245' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __BlendProfile_246) == 0x000088, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__BlendProfile_246' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __CurveFloat_247) == 0x000090, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__CurveFloat_247' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __BoolProperty_248) == 0x000098, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__BoolProperty_248' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __EnumProperty_249) == 0x000099, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__EnumProperty_249' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __EnumProperty_250) == 0x00009A, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__EnumProperty_250' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __ArrayProperty_251) == 0x0000A0, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__ArrayProperty_251' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_252) == 0x0000B0, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_252' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __IntProperty_253) == 0x0000B8, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__IntProperty_253' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_254) == 0x0000BC, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_254' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __NameProperty_255) == 0x0000C4, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__NameProperty_255' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __IntProperty_256) == 0x0000CC, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__IntProperty_256' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, __StructProperty_257) == 0x0000D0, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::__StructProperty_257' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0000F0, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000170, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct ABP_SkeletonCrossbowman.ABP_SkeletonCrossbowman_C.AnimBlueprintGeneratedMutableData
// 0x000B (0x000C - 0x0001)
struct ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_591D[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty;                                   // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_1;                                  // 0x0009(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData) == 0x000004, "Wrong alignment on ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData) == 0x00000C, "Wrong size on ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData, __FloatProperty) == 0x000004, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData::__FloatProperty' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000008, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");
static_assert(offsetof(ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData, __BoolProperty_1) == 0x000009, "Member 'ABP_SkeletonCrossbowman::FAnimBlueprintGeneratedMutableData::__BoolProperty_1' has a wrong offset!");

}

