#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_IceHarpy

#include "Basic.hpp"

#include "ABP_IceHarpy_classes.hpp"
#include "ABP_IceHarpy_parameters.hpp"


namespace SDK
{

// Function ABP_IceHarpy.ABP_IceHarpy_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_IceHarpy_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_IceHarpy_C", "AnimGraph");

	Params::ABP_IceHarpy_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_IceHarpy.ABP_IceHarpy_C.ExecuteUbergraph_ABP_IceHarpy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_IceHarpy_C::ExecuteUbergraph_ABP_IceHarpy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_IceHarpy_C", "ExecuteUbergraph_ABP_IceHarpy");

	Params::ABP_IceHarpy_C_ExecuteUbergraph_ABP_IceHarpy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

