#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AoeDefineBase

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.Add GameplayCue Location
// 0x00F0 (0x00F0 - 0x0000)
struct BP_AoeDefineBase_C_Add_GameplayCue_Location final
{
public:
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x0018(0x00D8)(ContainsInstancedReference)
};
static_assert(alignof(BP_AoeDefineBase_C_Add_GameplayCue_Location) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_Add_GameplayCue_Location");
static_assert(sizeof(BP_AoeDefineBase_C_Add_GameplayCue_Location) == 0x0000F0, "Wrong size on BP_AoeDefineBase_C_Add_GameplayCue_Location");
static_assert(offsetof(BP_AoeDefineBase_C_Add_GameplayCue_Location, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000000, "Member 'BP_AoeDefineBase_C_Add_GameplayCue_Location::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Add_GameplayCue_Location, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x000018, "Member 'BP_AoeDefineBase_C_Add_GameplayCue_Location::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.AddBeginOverlapActor
// 0x0008 (0x0008 - 0x0000)
struct BP_AoeDefineBase_C_AddBeginOverlapActor final
{
public:
	class ADCCharacterBase*                       CharacterBase;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_AddBeginOverlapActor) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_AddBeginOverlapActor");
static_assert(sizeof(BP_AoeDefineBase_C_AddBeginOverlapActor) == 0x000008, "Wrong size on BP_AoeDefineBase_C_AddBeginOverlapActor");
static_assert(offsetof(BP_AoeDefineBase_C_AddBeginOverlapActor, CharacterBase) == 0x000000, "Member 'BP_AoeDefineBase_C_AddBeginOverlapActor::CharacterBase' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.ExecuteUbergraph_BP_AoeDefineBase
// 0x01D8 (0x01D8 - 0x0000)
struct BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3881[0x3];                                     // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADCCharacterBase*                       K2Node_Event_CharacterBase_1;                      // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADCCharacterBase*                       K2Node_Event_CharacterBase;                        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGameplayTagValid_ReturnValue;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGameplayTagValid_ReturnValue_1;         // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_DoubleDouble_ReturnValue;        // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3882[0x5];                                     // 0x003B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x0058(0x00D8)(ContainsInstancedReference)
	bool                                          CallFunc_IsGameplayTagValid_ReturnValue_2;         // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3883[0x2];                                     // 0x0132(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0134(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0148(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3884[0x3];                                     // 0x0159(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue_1;             // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3885[0x2];                                     // 0x0162(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3886[0x3];                                     // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x016C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x017C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3887[0x3];                                     // 0x017D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0180(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3888[0x3];                                     // 0x0195(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityAsync_WaitGameplayTagAdded*     CallFunc_WaitGameplayTagAddToActor_ReturnValue;    // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3889[0x3];                                     // 0x01A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x01A4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_388A[0x4];                                     // 0x01B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ADCCharacterBase*                       CallFunc_Array_Get_Item;                           // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_2;            // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast_1;            // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast_2;            // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase");
static_assert(sizeof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase) == 0x0001D8, "Wrong size on BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, EntryPoint) == 0x000000, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Subtract_IntInt_ReturnValue) == 0x00000C, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000020, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, Temp_int_Variable) == 0x000024, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_Event_CharacterBase_1) == 0x000028, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_Event_CharacterBase_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_Event_CharacterBase) == 0x000030, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_Event_CharacterBase' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_IsGameplayTagValid_ReturnValue) == 0x000038, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_IsGameplayTagValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_IsGameplayTagValid_ReturnValue_1) == 0x000039, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_IsGameplayTagValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_NotEqual_DoubleDouble_ReturnValue) == 0x00003A, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_NotEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000040, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x000058, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_IsGameplayTagValid_ReturnValue_2) == 0x000130, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_IsGameplayTagValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_HasAuthority_ReturnValue) == 0x000131, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate_1) == 0x000134, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Add_IntInt_ReturnValue) == 0x000144, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate_2) == 0x000148, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_Contains_ReturnValue) == 0x000158, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_AddUnique_ReturnValue) == 0x00015C, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_Contains_ReturnValue_1) == 0x000160, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_RemoveItem_ReturnValue) == 0x000161, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000164, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000168, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate_3) == 0x00016C, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00017C, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate_4) == 0x000180, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, Temp_int_Variable_1) == 0x000190, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x000194, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_WaitGameplayTagAddToActor_ReturnValue) == 0x000198, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_WaitGameplayTagAddToActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_IsValid_ReturnValue) == 0x0001A0, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, K2Node_CreateDelegate_OutputDelegate_5) == 0x0001A4, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_Get_Item) == 0x0001B8, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Array_Length_ReturnValue) == 0x0001C0, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Subtract_IntInt_ReturnValue_2) == 0x0001C4, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Subtract_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Max_ReturnValue) == 0x0001C8, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Delay_Duration_ImplicitCast) == 0x0001CC, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Delay_Duration_ImplicitCast_1) == 0x0001D0, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Delay_Duration_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase, CallFunc_Delay_Duration_ImplicitCast_2) == 0x0001D4, "Member 'BP_AoeDefineBase_C_ExecuteUbergraph_BP_AoeDefineBase::CallFunc_Delay_Duration_ImplicitCast_2' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.Remove
// 0x0048 (0x0048 - 0x0000)
struct BP_AoeDefineBase_C_Remove final
{
public:
	class ADCCharacterBase*                       InputPin;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_Map_Find_Value;                           // 0x000C(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_388B[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_Array_Get_Item;                           // 0x0024(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RemoveActiveGameplayEffect_ReturnValue;   // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_388C[0x1];                                     // 0x002F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_Map_Find_Value_1;                         // 0x0034(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_388D[0x3];                                     // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RemoveGameplayTag_ReturnValue;            // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_Remove) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_Remove");
static_assert(sizeof(BP_AoeDefineBase_C_Remove) == 0x000048, "Wrong size on BP_AoeDefineBase_C_Remove");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, InputPin) == 0x000000, "Member 'BP_AoeDefineBase_C_Remove::InputPin' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Map_Find_Value) == 0x00000C, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Map_Find_ReturnValue) == 0x000014, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Subtract_IntInt_ReturnValue) == 0x000018, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Max_ReturnValue) == 0x00001C, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, Temp_int_Array_Index_Variable) == 0x000020, "Member 'BP_AoeDefineBase_C_Remove::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Array_Get_Item) == 0x000024, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Array_RemoveItem_ReturnValue) == 0x00002C, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_RemoveActiveGameplayEffect_ReturnValue) == 0x00002D, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_RemoveActiveGameplayEffect_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Map_Remove_ReturnValue) == 0x00002E, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, Temp_int_Loop_Counter_Variable) == 0x000030, "Member 'BP_AoeDefineBase_C_Remove::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Map_Find_Value_1) == 0x000034, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Map_Find_ReturnValue_1) == 0x00003C, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000040, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_RemoveGameplayTag_ReturnValue) == 0x000044, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_RemoveGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Remove, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000045, "Member 'BP_AoeDefineBase_C_Remove::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.RemoveEndOverlapActor
// 0x0008 (0x0008 - 0x0000)
struct BP_AoeDefineBase_C_RemoveEndOverlapActor final
{
public:
	class ADCCharacterBase*                       CharacterBase;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_RemoveEndOverlapActor) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_RemoveEndOverlapActor");
static_assert(sizeof(BP_AoeDefineBase_C_RemoveEndOverlapActor) == 0x000008, "Wrong size on BP_AoeDefineBase_C_RemoveEndOverlapActor");
static_assert(offsetof(BP_AoeDefineBase_C_RemoveEndOverlapActor, CharacterBase) == 0x000000, "Member 'BP_AoeDefineBase_C_RemoveEndOverlapActor::CharacterBase' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.Set Collision Profile Activate
// 0x0008 (0x0008 - 0x0000)
struct BP_AoeDefineBase_C_Set_Collision_Profile_Activate final
{
public:
	class UPrimitiveComponent*                    Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_Set_Collision_Profile_Activate) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_Set_Collision_Profile_Activate");
static_assert(sizeof(BP_AoeDefineBase_C_Set_Collision_Profile_Activate) == 0x000008, "Wrong size on BP_AoeDefineBase_C_Set_Collision_Profile_Activate");
static_assert(offsetof(BP_AoeDefineBase_C_Set_Collision_Profile_Activate, Target) == 0x000000, "Member 'BP_AoeDefineBase_C_Set_Collision_Profile_Activate::Target' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.Set Collision Profile Deactivate
// 0x0008 (0x0008 - 0x0000)
struct BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate final
{
public:
	class UPrimitiveComponent*                    Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate");
static_assert(sizeof(BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate) == 0x000008, "Wrong size on BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate");
static_assert(offsetof(BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate, Target) == 0x000000, "Member 'BP_AoeDefineBase_C_Set_Collision_Profile_Deactivate::Target' has a wrong offset!");

// Function BP_AoeDefineBase.BP_AoeDefineBase_C.Trigger
// 0x00E0 (0x00E0 - 0x0000)
struct BP_AoeDefineBase_C_Trigger final
{
public:
	class ADCCharacterBase*                       Input_Pin;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_388E[0x3];                                     // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x0028(0x00B0)()
	int32                                         CallFunc_Max_ReturnValue;                          // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AoeDefineBase_C_Trigger) == 0x000008, "Wrong alignment on BP_AoeDefineBase_C_Trigger");
static_assert(sizeof(BP_AoeDefineBase_C_Trigger) == 0x0000E0, "Wrong size on BP_AoeDefineBase_C_Trigger");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, Input_Pin) == 0x000000, "Member 'BP_AoeDefineBase_C_Trigger::Input_Pin' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'BP_AoeDefineBase_C_Trigger::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_Subtract_IntInt_ReturnValue) == 0x00000C, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000010, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, Temp_int_Array_Index_Variable) == 0x000014, "Member 'BP_AoeDefineBase_C_Trigger::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_Array_Get_Item) == 0x000018, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000024, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, K2Node_MakeStruct_GameplayEventData) == 0x000028, "Member 'BP_AoeDefineBase_C_Trigger::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");
static_assert(offsetof(BP_AoeDefineBase_C_Trigger, CallFunc_Max_ReturnValue) == 0x0000D8, "Member 'BP_AoeDefineBase_C_Trigger::CallFunc_Max_ReturnValue' has a wrong offset!");

}

