#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleAxe_Unique

#include "Basic.hpp"

#include "BP_UniqueItemActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleAxe_Unique.BP_BattleAxe_Unique_C
// 0x0010 (0x05B0 - 0x05A0)
class ABP_BattleAxe_Unique_C final : public ABP_UniqueItemActor_C
{
public:
	class UNiagaraComponent*                      FXS_EchoOfScreams_Feature;                         // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattleAxe_Unique_C">();
	}
	static class ABP_BattleAxe_Unique_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattleAxe_Unique_C>();
	}
};
static_assert(alignof(ABP_BattleAxe_Unique_C) == 0x000008, "Wrong alignment on ABP_BattleAxe_Unique_C");
static_assert(sizeof(ABP_BattleAxe_Unique_C) == 0x0005B0, "Wrong size on ABP_BattleAxe_Unique_C");
static_assert(offsetof(ABP_BattleAxe_Unique_C, FXS_EchoOfScreams_Feature) == 0x0005A0, "Member 'ABP_BattleAxe_Unique_C::FXS_EchoOfScreams_Feature' has a wrong offset!");
static_assert(offsetof(ABP_BattleAxe_Unique_C, Niagara) == 0x0005A8, "Member 'ABP_BattleAxe_Unique_C::Niagara' has a wrong offset!");

}

