#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CofferSmall_HR

#include "Basic.hpp"

#include "BP_CofferSmall_HR_classes.hpp"
#include "BP_CofferSmall_HR_parameters.hpp"


namespace SDK
{

// Function BP_CofferSmall_HR.BP_CofferSmall_HR_C.ExecuteUbergraph_BP_CofferSmall_HR
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CofferSmall_HR_C::ExecuteUbergraph_BP_CofferSmall_HR(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CofferSmall_HR_C", "ExecuteUbergraph_BP_CofferSmall_HR");

	Params::BP_CofferSmall_HR_C_ExecuteUbergraph_BP_CofferSmall_HR Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CofferSmall_HR.BP_CofferSmall_HR_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CofferSmall_HR_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CofferSmall_HR_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

