#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CobaltOre_HR

#include "Basic.hpp"

#include "BP_OreBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CobaltOre_HR.BP_CobaltOre_HR_C
// 0x0010 (0x04F8 - 0x04E8)
class ABP_CobaltOre_HR_C final : public ABP_OreBase_C
{
public:
	class UDCGeometryCollectionComponent*         GC_RubysilverOre_Default;                          // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_CobaltOre;                                      // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CobaltOre_HR_C">();
	}
	static class ABP_CobaltOre_HR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CobaltOre_HR_C>();
	}
};
static_assert(alignof(ABP_CobaltOre_HR_C) == 0x000008, "Wrong alignment on ABP_CobaltOre_HR_C");
static_assert(sizeof(ABP_CobaltOre_HR_C) == 0x0004F8, "Wrong size on ABP_CobaltOre_HR_C");
static_assert(offsetof(ABP_CobaltOre_HR_C, GC_RubysilverOre_Default) == 0x0004E8, "Member 'ABP_CobaltOre_HR_C::GC_RubysilverOre_Default' has a wrong offset!");
static_assert(offsetof(ABP_CobaltOre_HR_C, SM_CobaltOre) == 0x0004F0, "Member 'ABP_CobaltOre_HR_C::SM_CobaltOre' has a wrong offset!");

}

