#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CampfireProp

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_CampfireProp.BP_CampfireProp_C.ExecuteUbergraph_BP_CampfireProp
// 0x0068 (0x0068 - 0x0000)
struct BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C1A[0x3];                                     // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_Event_InGameplayTag;                        // 0x0014(0x0008)(ConstParm, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_InCount;                              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C1B[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue_1;                   // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C1C[0x6];                                     // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStaticMaterial>                CallFunc_GetStaticMaterials_ReturnValue;           // 0x0038(0x0010)(ConstParm, ReferenceParm)
	class UMaterialInterface*                     CallFunc_GetMaterial_ReturnValue;                  // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C1D[0x2];                                     // 0x0056(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetIntensity_NewIntensity_ImplicitCast;   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp) == 0x000008, "Wrong alignment on BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp");
static_assert(sizeof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp) == 0x000068, "Wrong size on BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, EntryPoint) == 0x000000, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_HasAuthority_ReturnValue) == 0x000010, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, K2Node_Event_InGameplayTag) == 0x000014, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::K2Node_Event_InGameplayTag' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, K2Node_Event_InCount) == 0x00001C, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::K2Node_Event_InCount' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Greater_IntInt_ReturnValue) == 0x000020, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000021, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000022, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_HasAuthority_ReturnValue_1) == 0x000023, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000028, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_IsServer_ReturnValue) == 0x000030, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_IsServer_ReturnValue_1) == 0x000031, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_IsServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_GetStaticMaterials_ReturnValue) == 0x000038, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_GetStaticMaterials_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_GetMaterial_ReturnValue) == 0x000048, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_GetMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Less_IntInt_ReturnValue) == 0x000054, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_SetStaticMesh_ReturnValue) == 0x000055, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x000058, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp, CallFunc_SetIntensity_NewIntensity_ImplicitCast) == 0x000060, "Member 'BP_CampfireProp_C_ExecuteUbergraph_BP_CampfireProp::CallFunc_SetIntensity_NewIntensity_ImplicitCast' has a wrong offset!");

// Function BP_CampfireProp.BP_CampfireProp_C.GameplayTagUpdated
// 0x000C (0x000C - 0x0000)
struct BP_CampfireProp_C_GameplayTagUpdated final
{
public:
	struct FGameplayTag                           InGameplayTag;                                     // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	int32                                         InCount;                                           // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CampfireProp_C_GameplayTagUpdated) == 0x000004, "Wrong alignment on BP_CampfireProp_C_GameplayTagUpdated");
static_assert(sizeof(BP_CampfireProp_C_GameplayTagUpdated) == 0x00000C, "Wrong size on BP_CampfireProp_C_GameplayTagUpdated");
static_assert(offsetof(BP_CampfireProp_C_GameplayTagUpdated, InGameplayTag) == 0x000000, "Member 'BP_CampfireProp_C_GameplayTagUpdated::InGameplayTag' has a wrong offset!");
static_assert(offsetof(BP_CampfireProp_C_GameplayTagUpdated, InCount) == 0x000008, "Member 'BP_CampfireProp_C_GameplayTagUpdated::InCount' has a wrong offset!");

}

