#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ElvenTorchHolder

#include "Basic.hpp"

#include "BP_TorchHolder_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ElvenTorchHolder.BP_ElvenTorchHolder_C
// 0x0000 (0x05A8 - 0x05A8)
class ABP_ElvenTorchHolder_C final : public ABP_TorchHolder_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ElvenTorchHolder_C">();
	}
	static class ABP_ElvenTorchHolder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ElvenTorchHolder_C>();
	}
};
static_assert(alignof(ABP_ElvenTorchHolder_C) == 0x000008, "Wrong alignment on ABP_ElvenTorchHolder_C");
static_assert(sizeof(ABP_ElvenTorchHolder_C) == 0x0005A8, "Wrong size on ABP_ElvenTorchHolder_C");

}

