#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FrostWalker_Nightmare

#include "Basic.hpp"

#include "BP_FrostWalker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FrostWalker_Nightmare.BP_FrostWalker_Nightmare_C
// 0x0000 (0x1470 - 0x1470)
class ABP_FrostWalker_Nightmare_C final : public ABP_FrostWalker_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FrostWalker_Nightmare_C">();
	}
	static class ABP_FrostWalker_Nightmare_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FrostWalker_Nightmare_C>();
	}
};
static_assert(alignof(ABP_FrostWalker_Nightmare_C) == 0x000010, "Wrong alignment on ABP_FrostWalker_Nightmare_C");
static_assert(sizeof(ABP_FrostWalker_Nightmare_C) == 0x001470, "Wrong size on ABP_FrostWalker_Nightmare_C");

}

