#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IceAbyssRoaster01_On

#include "Basic.hpp"

#include "BP_LightSourceBase_classes.hpp"
#include "Engine_structs.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IceAbyssRoaster01_On.BP_IceAbyssRoaster01_On_C
// 0x00B0 (0x05A0 - 0x04F0)
class ABP_IceAbyssRoaster01_On_C final : public ABP_LightSourceBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_IceAbyssRoaster01_On_C;          // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      FXS_IceLamp_003;                                   // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard5;                                // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard4;                                // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard3;                                // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard2;                                // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard;                                 // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialBillboardComponent*            MaterialBillboard1;                                // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Sphere;                                            // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Torch;                                             // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_1_FX_Alpah_2DD44DA94940A1488ECD86A2A19A71AE; // 0x0540(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_1_Power3_2DD44DA94940A1488ECD86A2A19A71AE; // 0x0544(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_1_Power2_2DD44DA94940A1488ECD86A2A19A71AE; // 0x0548(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_1______0_2DD44DA94940A1488ECD86A2A19A71AE; // 0x054C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_1__Direction_2DD44DA94940A1488ECD86A2A19A71AE; // 0x0550(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4FD9[0x7];                                     // 0x0551(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_1;                                        // 0x0558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_FX_Alpha_77AA14514F472EA56E9696AC69BF641E; // 0x0560(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Power3_77AA14514F472EA56E9696AC69BF641E; // 0x0564(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Power2_77AA14514F472EA56E9696AC69BF641E; // 0x0568(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0______0_77AA14514F472EA56E9696AC69BF641E; // 0x056C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_77AA14514F472EA56E9696AC69BF641E; // 0x0570(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4FDA[0x7];                                     // 0x0571(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0578(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsOverlapped;                                     // 0x0580(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4FDB[0x7];                                     // 0x0581(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialBillboardComponent*>    MaterialBillboards;                                // 0x0588(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UMaterialInstanceDynamic*               DynamicMaterialInstance;                           // 0x0598(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_TorchOn_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__BP_TorchOn_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void ExecuteUbergraph_BP_IceAbyssRoaster01_On(int32 EntryPoint);
	void GameplayTagUpdated(const struct FGameplayTag& InGameplayTag, int32 InCount);
	void InteractSucceed(class AActor* Interacter, const struct FGameplayTag& StateTag, const struct FGameplayTag& TriggerTag, const struct FHitResult& HitResult);
	void ReceiveBeginPlay();
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_1__FinishedFunc();
	void Timeline_1__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IceAbyssRoaster01_On_C">();
	}
	static class ABP_IceAbyssRoaster01_On_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_IceAbyssRoaster01_On_C>();
	}
};
static_assert(alignof(ABP_IceAbyssRoaster01_On_C) == 0x000008, "Wrong alignment on ABP_IceAbyssRoaster01_On_C");
static_assert(sizeof(ABP_IceAbyssRoaster01_On_C) == 0x0005A0, "Wrong size on ABP_IceAbyssRoaster01_On_C");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, UberGraphFrame_BP_IceAbyssRoaster01_On_C) == 0x0004F0, "Member 'ABP_IceAbyssRoaster01_On_C::UberGraphFrame_BP_IceAbyssRoaster01_On_C' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, FXS_IceLamp_003) == 0x0004F8, "Member 'ABP_IceAbyssRoaster01_On_C::FXS_IceLamp_003' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard5) == 0x000500, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard5' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard4) == 0x000508, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard4' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard3) == 0x000510, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard3' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard2) == 0x000518, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard2' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard) == 0x000520, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboard1) == 0x000528, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboard1' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Sphere) == 0x000530, "Member 'ABP_IceAbyssRoaster01_On_C::Sphere' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Torch) == 0x000538, "Member 'ABP_IceAbyssRoaster01_On_C::Torch' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1_FX_Alpah_2DD44DA94940A1488ECD86A2A19A71AE) == 0x000540, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1_FX_Alpah_2DD44DA94940A1488ECD86A2A19A71AE' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1_Power3_2DD44DA94940A1488ECD86A2A19A71AE) == 0x000544, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1_Power3_2DD44DA94940A1488ECD86A2A19A71AE' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1_Power2_2DD44DA94940A1488ECD86A2A19A71AE) == 0x000548, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1_Power2_2DD44DA94940A1488ECD86A2A19A71AE' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1______0_2DD44DA94940A1488ECD86A2A19A71AE) == 0x00054C, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1______0_2DD44DA94940A1488ECD86A2A19A71AE' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1__Direction_2DD44DA94940A1488ECD86A2A19A71AE) == 0x000550, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1__Direction_2DD44DA94940A1488ECD86A2A19A71AE' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_1) == 0x000558, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_1' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0_FX_Alpha_77AA14514F472EA56E9696AC69BF641E) == 0x000560, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0_FX_Alpha_77AA14514F472EA56E9696AC69BF641E' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0_Power3_77AA14514F472EA56E9696AC69BF641E) == 0x000564, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0_Power3_77AA14514F472EA56E9696AC69BF641E' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0_Power2_77AA14514F472EA56E9696AC69BF641E) == 0x000568, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0_Power2_77AA14514F472EA56E9696AC69BF641E' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0______0_77AA14514F472EA56E9696AC69BF641E) == 0x00056C, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0______0_77AA14514F472EA56E9696AC69BF641E' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0__Direction_77AA14514F472EA56E9696AC69BF641E) == 0x000570, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0__Direction_77AA14514F472EA56E9696AC69BF641E' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, Timeline_0) == 0x000578, "Member 'ABP_IceAbyssRoaster01_On_C::Timeline_0' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, bIsOverlapped) == 0x000580, "Member 'ABP_IceAbyssRoaster01_On_C::bIsOverlapped' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, MaterialBillboards) == 0x000588, "Member 'ABP_IceAbyssRoaster01_On_C::MaterialBillboards' has a wrong offset!");
static_assert(offsetof(ABP_IceAbyssRoaster01_On_C, DynamicMaterialInstance) == 0x000598, "Member 'ABP_IceAbyssRoaster01_On_C::DynamicMaterialInstance' has a wrong offset!");

}

