#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lifeleaf_N

#include "Basic.hpp"

#include "BP_HerbBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lifeleaf_N.BP_Lifeleaf_N_C
// 0x0000 (0x0508 - 0x0508)
class ABP_Lifeleaf_N_C final : public ABP_HerbBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Lifeleaf_N_C">();
	}
	static class ABP_Lifeleaf_N_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lifeleaf_N_C>();
	}
};
static_assert(alignof(ABP_Lifeleaf_N_C) == 0x000008, "Wrong alignment on ABP_Lifeleaf_N_C");
static_assert(sizeof(ABP_Lifeleaf_N_C) == 0x000508, "Wrong size on ABP_Lifeleaf_N_C");

}

