#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LivingStatue_Nightmare

#include "Basic.hpp"

#include "BP_LivingStatue_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LivingStatue_Nightmare.BP_LivingStatue_Nightmare_C
// 0x0000 (0x15A0 - 0x15A0)
class ABP_LivingStatue_Nightmare_C final : public ABP_LivingStatue_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LivingStatue_Nightmare_C">();
	}
	static class ABP_LivingStatue_Nightmare_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LivingStatue_Nightmare_C>();
	}
};
static_assert(alignof(ABP_LivingStatue_Nightmare_C) == 0x000010, "Wrong alignment on ABP_LivingStatue_Nightmare_C");
static_assert(sizeof(ABP_LivingStatue_Nightmare_C) == 0x0015A0, "Wrong size on ABP_LivingStatue_Nightmare_C");

}

