#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OrnateChestLarge_N0

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function BP_OrnateChestLarge_N0.BP_OrnateChestLarge_N0_C.ExecuteUbergraph_BP_OrnateChestLarge_N0
// 0x0058 (0x0058 - 0x0000)
struct BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5300[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FGameplayTag, class UGeometryCollectionComponent*> K2Node_MakeMap_Map;                                // 0x0008(0x0050)(ContainsInstancedReference)
};
static_assert(alignof(BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0) == 0x000008, "Wrong alignment on BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0");
static_assert(sizeof(BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0) == 0x000058, "Wrong size on BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0");
static_assert(offsetof(BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0, EntryPoint) == 0x000000, "Member 'BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0, K2Node_MakeMap_Map) == 0x000008, "Member 'BP_OrnateChestLarge_N0_C_ExecuteUbergraph_BP_OrnateChestLarge_N0::K2Node_MakeMap_Map' has a wrong offset!");

}

