#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RayOfDarknessEndPoint

#include "Basic.hpp"

#include "BP_RayOfDarknessEndPoint_classes.hpp"
#include "BP_RayOfDarknessEndPoint_parameters.hpp"


namespace SDK
{

// Function BP_RayOfDarknessEndPoint.BP_RayOfDarknessEndPoint_C.ExecuteUbergraph_BP_RayOfDarknessEndPoint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RayOfDarknessEndPoint_C::ExecuteUbergraph_BP_RayOfDarknessEndPoint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RayOfDarknessEndPoint_C", "ExecuteUbergraph_BP_RayOfDarknessEndPoint");

	Params::BP_RayOfDarknessEndPoint_C_ExecuteUbergraph_BP_RayOfDarknessEndPoint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RayOfDarknessEndPoint.BP_RayOfDarknessEndPoint_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RayOfDarknessEndPoint_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RayOfDarknessEndPoint_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RayOfDarknessEndPoint.BP_RayOfDarknessEndPoint_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RayOfDarknessEndPoint_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RayOfDarknessEndPoint_C", "ReceiveEndPlay");

	Params::BP_RayOfDarknessEndPoint_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}

}

