#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThornyBramble

#include "Basic.hpp"

#include "DungeonCrawler_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "AkAudio_structs.hpp"


namespace SDK::Params
{

// Function BP_ThornyBramble.BP_ThornyBramble_C.ExecuteUbergraph_BP_ThornyBramble
// 0x0470 (0x0470 - 0x0000)
struct BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E4[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable;                            // 0x0008(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E5[0x2];                                     // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable_1;                          // 0x001C(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Event_InGameplayTag;                        // 0x002C(0x0008)(ConstParm, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_InCount;                              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_ExhaustedTime;                        // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UGameplayEffect>            K2Node_Event_GameplayEffectClass;                  // 0x0040(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	struct FDCGameplayEffectContext               K2Node_Event_EffectContext;                        // 0x0048(0x0420)(ContainsInstancedReference)
	int32                                         CallFunc_PostAkEvent_ReturnValue;                  // 0x0468(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostAkEvent_ReturnValue_1;                // 0x046C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble");
static_assert(sizeof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble) == 0x000470, "Wrong size on BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, EntryPoint) == 0x000000, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_HasAuthority_ReturnValue) == 0x000004, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, Temp_delegate_Variable) == 0x000008, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::Temp_delegate_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, Temp_bool_Variable) == 0x000018, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_Not_PreBool_ReturnValue) == 0x000019, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, Temp_delegate_Variable_1) == 0x00001C, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::Temp_delegate_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, K2Node_Event_InGameplayTag) == 0x00002C, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::K2Node_Event_InGameplayTag' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, K2Node_Event_InCount) == 0x000034, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::K2Node_Event_InCount' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_Greater_IntInt_ReturnValue) == 0x000038, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000039, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_HasAuthority_ReturnValue_1) == 0x00003A, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_HasAuthority_ReturnValue_2) == 0x00003B, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, K2Node_Event_ExhaustedTime) == 0x00003C, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::K2Node_Event_ExhaustedTime' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, K2Node_Event_GameplayEffectClass) == 0x000040, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::K2Node_Event_GameplayEffectClass' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, K2Node_Event_EffectContext) == 0x000048, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::K2Node_Event_EffectContext' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_PostAkEvent_ReturnValue) == 0x000468, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_PostAkEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble, CallFunc_PostAkEvent_ReturnValue_1) == 0x00046C, "Member 'BP_ThornyBramble_C_ExecuteUbergraph_BP_ThornyBramble::CallFunc_PostAkEvent_ReturnValue_1' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.GameplayTagUpdated
// 0x000C (0x000C - 0x0000)
struct BP_ThornyBramble_C_GameplayTagUpdated final
{
public:
	struct FGameplayTag                           InGameplayTag;                                     // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	int32                                         InCount;                                           // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_GameplayTagUpdated) == 0x000004, "Wrong alignment on BP_ThornyBramble_C_GameplayTagUpdated");
static_assert(sizeof(BP_ThornyBramble_C_GameplayTagUpdated) == 0x00000C, "Wrong size on BP_ThornyBramble_C_GameplayTagUpdated");
static_assert(offsetof(BP_ThornyBramble_C_GameplayTagUpdated, InGameplayTag) == 0x000000, "Member 'BP_ThornyBramble_C_GameplayTagUpdated::InGameplayTag' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GameplayTagUpdated, InCount) == 0x000008, "Member 'BP_ThornyBramble_C_GameplayTagUpdated::InCount' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.GetLastNormalizedProgression
// 0x0050 (0x0050 - 0x0000)
struct BP_ThornyBramble_C_GetLastNormalizedProgression final
{
public:
	double                                        Last_Time_Delay;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Last_Transition_Duration;                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Last_Triggered_Time;                               // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsActivated;                                       // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E6[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NewParam;                                          // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetTimeSeconds_ReturnValue;               // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_GetLastNormalizedProgression) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_GetLastNormalizedProgression");
static_assert(sizeof(BP_ThornyBramble_C_GetLastNormalizedProgression) == 0x000050, "Wrong size on BP_ThornyBramble_C_GetLastNormalizedProgression");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, Last_Time_Delay) == 0x000000, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::Last_Time_Delay' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, Last_Transition_Duration) == 0x000008, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::Last_Transition_Duration' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, Last_Triggered_Time) == 0x000010, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::Last_Triggered_Time' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, IsActivated) == 0x000018, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::IsActivated' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, NewParam) == 0x000020, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::NewParam' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000028, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, CallFunc_GetTimeSeconds_ReturnValue) == 0x000030, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::CallFunc_GetTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000038, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000040, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_GetLastNormalizedProgression, CallFunc_FClamp_ReturnValue) == 0x000048, "Member 'BP_ThornyBramble_C_GetLastNormalizedProgression::CallFunc_FClamp_ReturnValue' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.GetRecoveryTime
// 0x0008 (0x0008 - 0x0000)
struct BP_ThornyBramble_C_GetRecoveryTime final
{
public:
	double                                        Result;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_GetRecoveryTime) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_GetRecoveryTime");
static_assert(sizeof(BP_ThornyBramble_C_GetRecoveryTime) == 0x000008, "Wrong size on BP_ThornyBramble_C_GetRecoveryTime");
static_assert(offsetof(BP_ThornyBramble_C_GetRecoveryTime, Result) == 0x000000, "Member 'BP_ThornyBramble_C_GetRecoveryTime::Result' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.InitializeMeshArray
// 0x0030 (0x0030 - 0x0000)
struct BP_ThornyBramble_C_InitializeMeshArray final
{
public:
	int32                                         Temp_int_Variable;                                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumChildrenComponents_ReturnValue;     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_GetChildComponent_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E7[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   K2Node_DynamicCast_As___________;                  // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E8[0x2];                                     // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_InitializeMeshArray) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_InitializeMeshArray");
static_assert(sizeof(BP_ThornyBramble_C_InitializeMeshArray) == 0x000030, "Wrong size on BP_ThornyBramble_C_InitializeMeshArray");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, Temp_int_Variable) == 0x000000, "Member 'BP_ThornyBramble_C_InitializeMeshArray::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_GetNumChildrenComponents_ReturnValue) == 0x000004, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_GetNumChildrenComponents_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_GetChildComponent_ReturnValue) == 0x000008, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_GetChildComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_Subtract_IntInt_ReturnValue) == 0x000010, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, K2Node_DynamicCast_As___________) == 0x000018, "Member 'BP_ThornyBramble_C_InitializeMeshArray::K2Node_DynamicCast_As___________' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_ThornyBramble_C_InitializeMeshArray::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000021, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_Add_IntInt_ReturnValue) == 0x000024, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeMeshArray, CallFunc_Array_Add_ReturnValue) == 0x000028, "Member 'BP_ThornyBramble_C_InitializeMeshArray::CallFunc_Array_Add_ReturnValue' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.InitializeThornyBramblePrimitiveData
// 0x0070 (0x0070 - 0x0000)
struct BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData final
{
public:
	double                                        TransitionDuration;                                // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Delay;                                             // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxFrame;                                          // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EndFrame;                                          // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        StartFrame;                                        // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E9[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35EA[0x3];                                     // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast; // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast_1; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData");
static_assert(sizeof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData) == 0x000070, "Wrong size on BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, TransitionDuration) == 0x000000, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::TransitionDuration' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, Delay) == 0x000008, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::Delay' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, MaxFrame) == 0x000010, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::MaxFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, EndFrame) == 0x000018, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::EndFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, StartFrame) == 0x000020, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::StartFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, Temp_int_Array_Index_Variable) == 0x000028, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Add_IntInt_ReturnValue) == 0x000030, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_RandomFloatInRange_ReturnValue) == 0x000038, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000040, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Array_Add_ReturnValue) == 0x000048, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Array_Add_ReturnValue_1) == 0x00004C, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000050, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Array_Get_Item) == 0x000058, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Array_Length_ReturnValue) == 0x000060, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_Less_IntInt_ReturnValue) == 0x000064, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast) == 0x000068, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData, CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast_1) == 0x00006C, "Member 'BP_ThornyBramble_C_InitializeThornyBramblePrimitiveData::CallFunc_SetDefaultCustomPrimitiveDataFloat_Value_ImplicitCast_1' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.IsRecovery
// 0x0001 (0x0001 - 0x0000)
struct BP_ThornyBramble_C_IsRecovery final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_IsRecovery) == 0x000001, "Wrong alignment on BP_ThornyBramble_C_IsRecovery");
static_assert(sizeof(BP_ThornyBramble_C_IsRecovery) == 0x000001, "Wrong size on BP_ThornyBramble_C_IsRecovery");
static_assert(offsetof(BP_ThornyBramble_C_IsRecovery, Result) == 0x000000, "Member 'BP_ThornyBramble_C_IsRecovery::Result' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.OnImpactEnduranceExhausted
// 0x0430 (0x0430 - 0x0000)
struct BP_ThornyBramble_C_OnImpactEnduranceExhausted final
{
public:
	float                                         ExhaustedTime;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35EB[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UGameplayEffect>            GameplayEffectClass;                               // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	struct FDCGameplayEffectContext               EffectContext;                                     // 0x0010(0x0420)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};
static_assert(alignof(BP_ThornyBramble_C_OnImpactEnduranceExhausted) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_OnImpactEnduranceExhausted");
static_assert(sizeof(BP_ThornyBramble_C_OnImpactEnduranceExhausted) == 0x000430, "Wrong size on BP_ThornyBramble_C_OnImpactEnduranceExhausted");
static_assert(offsetof(BP_ThornyBramble_C_OnImpactEnduranceExhausted, ExhaustedTime) == 0x000000, "Member 'BP_ThornyBramble_C_OnImpactEnduranceExhausted::ExhaustedTime' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_OnImpactEnduranceExhausted, GameplayEffectClass) == 0x000008, "Member 'BP_ThornyBramble_C_OnImpactEnduranceExhausted::GameplayEffectClass' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_OnImpactEnduranceExhausted, EffectContext) == 0x000010, "Member 'BP_ThornyBramble_C_OnImpactEnduranceExhausted::EffectContext' has a wrong offset!");

// Function BP_ThornyBramble.BP_ThornyBramble_C.UpdateThornyBramblePrimitiveData
// 0x0078 (0x0078 - 0x0000)
struct BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData final
{
public:
	bool                                          IsActivate;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35EC[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Current_Playrate;                                  // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxFrame;                                          // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EndFrame;                                          // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        StartFrame;                                        // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetTimeSeconds_ReturnValue;               // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Array_Get_Item_1;                         // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Array_Get_Item_2;                         // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetTimeSeconds_ReturnValue_1;             // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetLastNormalizedProgression_NewParam;    // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35ED[0x3];                                     // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_1; // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_2; // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData) == 0x000008, "Wrong alignment on BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData");
static_assert(sizeof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData) == 0x000078, "Wrong size on BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, IsActivate) == 0x000000, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::IsActivate' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, Current_Playrate) == 0x000008, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::Current_Playrate' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, MaxFrame) == 0x000010, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::MaxFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, EndFrame) == 0x000018, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::EndFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, StartFrame) == 0x000020, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::StartFrame' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_GetTimeSeconds_ReturnValue) == 0x000028, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_GetTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, Temp_int_Array_Index_Variable) == 0x000034, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Array_Get_Item) == 0x000038, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Array_Get_Item_1) == 0x000040, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Array_Get_Item_2) == 0x000048, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_GetTimeSeconds_ReturnValue_1) == 0x000050, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_GetTimeSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_GetLastNormalizedProgression_NewParam) == 0x000058, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_GetLastNormalizedProgression_NewParam' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, Temp_int_Loop_Counter_Variable) == 0x000060, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Less_IntInt_ReturnValue) == 0x000064, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_Add_IntInt_ReturnValue) == 0x000068, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast) == 0x00006C, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_1) == 0x000070, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData, CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_2) == 0x000074, "Member 'BP_ThornyBramble_C_UpdateThornyBramblePrimitiveData::CallFunc_SetCustomPrimitiveDataFloat_Value_ImplicitCast_2' has a wrong offset!");

}

