#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wanted01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_PropsActorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Wanted01.BP_Wanted01_C
// 0x0028 (0x04E0 - 0x04B8)
class ABP_Wanted01_C final : public ABP_PropsActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Wanted01_C;                      // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   SM_Wanted01;                                       // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FPrimaryAssetId                        ScriptAssetID;                                     // 0x04C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         FontSize;                                          // 0x04D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Wanted01(int32 EntryPoint);
	void InteractSucceed(class AActor* Interacter, const struct FGameplayTag& StateTag, const struct FGameplayTag& TriggerTag, const struct FHitResult& HitResult);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Wanted01_C">();
	}
	static class ABP_Wanted01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Wanted01_C>();
	}
};
static_assert(alignof(ABP_Wanted01_C) == 0x000008, "Wrong alignment on ABP_Wanted01_C");
static_assert(sizeof(ABP_Wanted01_C) == 0x0004E0, "Wrong size on ABP_Wanted01_C");
static_assert(offsetof(ABP_Wanted01_C, UberGraphFrame_BP_Wanted01_C) == 0x0004B8, "Member 'ABP_Wanted01_C::UberGraphFrame_BP_Wanted01_C' has a wrong offset!");
static_assert(offsetof(ABP_Wanted01_C, SM_Wanted01) == 0x0004C0, "Member 'ABP_Wanted01_C::SM_Wanted01' has a wrong offset!");
static_assert(offsetof(ABP_Wanted01_C, ScriptAssetID) == 0x0004C8, "Member 'ABP_Wanted01_C::ScriptAssetID' has a wrong offset!");
static_assert(offsetof(ABP_Wanted01_C, FontSize) == 0x0004D8, "Member 'ABP_Wanted01_C::FontSize' has a wrong offset!");

}

