#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTD_CheckTargetDistanceToAttack

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BTD_CheckTargetDistanceToAttack.BTD_CheckTargetDistanceToAttack_C.PerformConditionCheckAI
// 0x0100 (0x0100 - 0x0000)
struct BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38AF[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_DCMonsterBaseWithOptions_C*         K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options; // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38B0[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_DCMonsterBaseWithOptions_C*         K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options_1; // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38B1[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue_1;              // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetCapsuleBottomLocation_ReturnValue;     // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_GetValueAsObject_ReturnValue;             // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADCCharacterBase*                       K2Node_DynamicCast_AsDCCharacter_Base;             // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38B2[0x3];                                     // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue_1;            // 0x0094(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38B3[0x4];                                     // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetCapsuleBottomLocation_ReturnValue_1;   // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_GetValueAsObject_ReturnValue_1;           // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue;              // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_DynamicCast_As__;                           // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38B4[0x6];                                     // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x00D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue_1;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_1;     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI) == 0x000008, "Wrong alignment on BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI");
static_assert(sizeof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI) == 0x000100, "Wrong size on BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, OwnerController) == 0x000000, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::OwnerController' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, ControlledPawn) == 0x000008, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::ControlledPawn' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, ReturnValue) == 0x000010, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetBlackboard_ReturnValue) == 0x000018, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options) == 0x000020, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000030, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options_1) == 0x000048, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_AsBP_DCMonster_Base_with_Options_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetBlackboard_ReturnValue_1) == 0x000058, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetBlackboard_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetCapsuleBottomLocation_ReturnValue) == 0x000060, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetCapsuleBottomLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_MakeLiteralName_ReturnValue) == 0x000078, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetValueAsObject_ReturnValue) == 0x000080, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetValueAsObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_AsDCCharacter_Base) == 0x000088, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_AsDCCharacter_Base' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_bSuccess_2) == 0x000090, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_MakeLiteralName_ReturnValue_1) == 0x000094, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_MakeLiteralName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetCapsuleBottomLocation_ReturnValue_1) == 0x0000A0, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetCapsuleBottomLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_GetValueAsObject_ReturnValue_1) == 0x0000B8, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_GetValueAsObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_Vector_Distance_ReturnValue) == 0x0000C0, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_As__) == 0x0000C8, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_As__' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, K2Node_DynamicCast_bSuccess_3) == 0x0000D0, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x0000D1, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0000D8, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_Vector_Distance_ReturnValue_1) == 0x0000F0, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_Vector_Distance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI, CallFunc_LessEqual_DoubleDouble_ReturnValue_1) == 0x0000F8, "Member 'BTD_CheckTargetDistanceToAttack_C_PerformConditionCheckAI::CallFunc_LessEqual_DoubleDouble_ReturnValue_1' has a wrong offset!");

}

