#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Backstep

#include "Basic.hpp"

#include "GA_Backstep_classes.hpp"
#include "GA_Backstep_parameters.hpp"


namespace SDK
{

// Function GA_Backstep.GA_Backstep_C.ExecuteUbergraph_GA_Backstep
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Backstep_C::ExecuteUbergraph_GA_Backstep(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Backstep_C", "ExecuteUbergraph_GA_Backstep");

	Params::GA_Backstep_C_ExecuteUbergraph_GA_Backstep Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Backstep.GA_Backstep_C.OnMovementModeChanged_FEDF92D84E71845950F099BA81D066CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EMovementMode                           PrevMovementMode                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMovementMode                           NewMovementMode                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Backstep_C::OnMovementModeChanged_FEDF92D84E71845950F099BA81D066CB(EMovementMode PrevMovementMode, EMovementMode NewMovementMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Backstep_C", "OnMovementModeChanged_FEDF92D84E71845950F099BA81D066CB");

	Params::GA_Backstep_C_OnMovementModeChanged_FEDF92D84E71845950F099BA81D066CB Parms{};

	Parms.PrevMovementMode = PrevMovementMode;
	Parms.NewMovementMode = NewMovementMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Backstep.GA_Backstep_C.ServerOnSkillActivate
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     SkillTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     CooldownTag                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGA_Backstep_C::ServerOnSkillActivate(const struct FGameplayTag& SkillTag, const struct FGameplayTag& CooldownTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Backstep_C", "ServerOnSkillActivate");

	Params::GA_Backstep_C_ServerOnSkillActivate Parms{};

	Parms.SkillTag = std::move(SkillTag);
	Parms.CooldownTag = std::move(CooldownTag);

	UObject::ProcessEvent(Func, &Parms);
}

}

