#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Banshee_PullingAttack

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_Banshee_PullingAttack.GA_Banshee_PullingAttack_C.AbilityActivated
// 0x00B0 (0x00B0 - 0x0000)
struct GA_Banshee_PullingAttack_C_AbilityActivated final
{
public:
	struct FGameplayEventData                     TriggerEventData;                                  // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_Banshee_PullingAttack_C_AbilityActivated) == 0x000008, "Wrong alignment on GA_Banshee_PullingAttack_C_AbilityActivated");
static_assert(sizeof(GA_Banshee_PullingAttack_C_AbilityActivated) == 0x0000B0, "Wrong size on GA_Banshee_PullingAttack_C_AbilityActivated");
static_assert(offsetof(GA_Banshee_PullingAttack_C_AbilityActivated, TriggerEventData) == 0x000000, "Member 'GA_Banshee_PullingAttack_C_AbilityActivated::TriggerEventData' has a wrong offset!");

// Function GA_Banshee_PullingAttack.GA_Banshee_PullingAttack_C.EventReceived_52C56E354E03ED821EAABF8666166BD0
// 0x00B8 (0x00B8 - 0x0000)
struct GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0 final
{
public:
	struct FGameplayTag                           EventTag;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     EventData;                                         // 0x0008(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0) == 0x000008, "Wrong alignment on GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0");
static_assert(sizeof(GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0) == 0x0000B8, "Wrong size on GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0");
static_assert(offsetof(GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0, EventTag) == 0x000000, "Member 'GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0::EventTag' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0, EventData) == 0x000008, "Member 'GA_Banshee_PullingAttack_C_EventReceived_52C56E354E03ED821EAABF8666166BD0::EventData' has a wrong offset!");

// Function GA_Banshee_PullingAttack.GA_Banshee_PullingAttack_C.ExecuteUbergraph_GA_Banshee_PullingAttack
// 0x0618 (0x0618 - 0x0000)
struct GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)> K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4909[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector_X;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490A[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490B[0x3];                                     // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490C[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_Event_TriggerEventData;                     // 0x0088(0x00B0)(ConstParm)
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Banshee_Common_C*                   K2Node_DynamicCast_AsBP_Banshee_Common;            // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x014A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490D[0x1];                                     // 0x014B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Multiply_IntInt_ReturnValue;              // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490E[0x4];                                     // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0162(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_490F[0x1];                                     // 0x0163(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Get_BB_Phase_Phase;                       // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4910[0x3];                                     // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_1;                               // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4911[0x4];                                     // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ADCCharacterBase*                       CallFunc_Array_Get_Item;                           // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4912[0x4];                                     // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x0190(0x00B0)()
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4913[0x4];                                     // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FActiveGameplayEffectHandle>    CallFunc_ApplyEffectContainer_ReturnValue;         // 0x0248(0x0010)(ReferenceParm)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4914[0x4];                                     // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0260(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput;    // 0x0278(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4915[0x7];                                     // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1; // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4916[0x7];                                     // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData_1;             // 0x02A0(0x00B0)()
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue_2; // 0x0350(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADCCharacterBase*                       CallFunc_Array_Get_Item_1;                         // 0x0358(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4917[0x4];                                     // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x0368(0x00D8)(ContainsInstancedReference)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0440(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4918[0x7];                                     // 0x0441(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDCAT_WaitForGameplayEvents*            CallFunc_WaitForGameplayEvents_ReturnValue;        // 0x0448(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0450(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4919[0x3];                                     // 0x0451(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0454(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_491A[0x4];                                     // 0x045C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     Temp_struct_Variable_1;                            // 0x0460(0x00B0)()
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0510(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_491B[0x3];                                     // 0x0511(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_CustomEvent_EventTag;                       // 0x0514(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_491C[0x4];                                     // 0x051C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_CustomEvent_EventData;                      // 0x0520(0x00B0)()
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x05D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue;              // 0x05E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_3;      // 0x05F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_4;      // 0x05F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0600(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0608(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_5;      // 0x0610(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack) == 0x000008, "Wrong alignment on GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack");
static_assert(sizeof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack) == 0x000618, "Wrong size on GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, EntryPoint) == 0x000000, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_BreakVector_X) == 0x000018, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_BreakVector_Y) == 0x000020, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_BreakVector_Z) == 0x000028, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Variable) == 0x000030, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000038, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000040, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x000048, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_RandomFloatInRange_ReturnValue) == 0x000050, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000058, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000060, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Loop_Counter_Variable) == 0x000068, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Subtract_IntInt_ReturnValue) == 0x00006C, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000070, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Array_Index_Variable) == 0x000074, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Loop_Counter_Variable_1) == 0x000078, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_IntInt_ReturnValue) == 0x00007C, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Array_Index_Variable_1) == 0x000080, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_Event_TriggerEventData) == 0x000088, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_Event_TriggerEventData' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x000138, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_DynamicCast_AsBP_Banshee_Common) == 0x000140, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_DynamicCast_AsBP_Banshee_Common' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_DynamicCast_bSuccess) == 0x000148, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_Event_bWasCancelled) == 0x000149, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_IsValid_ReturnValue) == 0x00014A, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_IntInt_ReturnValue_1) == 0x00014C, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_IntInt_ReturnValue) == 0x000150, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000158, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000160, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000161, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_BooleanOR_ReturnValue) == 0x000162, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Get_BB_Phase_Phase) == 0x000164, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Get_BB_Phase_Phase' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000168, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_IntInt_ReturnValue_2) == 0x00016C, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_SwitchInteger_CmpSuccess) == 0x000170, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_int_Variable_1) == 0x000174, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_IntInt_ReturnValue_3) == 0x000178, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Array_Get_Item) == 0x000180, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Array_Length_ReturnValue) == 0x000188, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_MakeStruct_GameplayEventData) == 0x000190, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000240, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_ApplyEffectContainer_ReturnValue) == 0x000248, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_ApplyEffectContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Max_ReturnValue) == 0x000258, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000260, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000278, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000288, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1) == 0x000290, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Not_PreBool_ReturnValue) == 0x000298, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_MakeStruct_GameplayEventData_1) == 0x0002A0, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_MakeStruct_GameplayEventData_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_GetAvatarActorFromActorInfo_ReturnValue_2) == 0x000350, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_GetAvatarActorFromActorInfo_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Array_Get_Item_1) == 0x000358, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Array_Length_ReturnValue_1) == 0x000360, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x000368, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Less_IntInt_ReturnValue) == 0x000440, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_WaitForGameplayEvents_ReturnValue) == 0x000448, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_WaitForGameplayEvents_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_IsValid_ReturnValue_1) == 0x000450, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_struct_Variable) == 0x000454, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, Temp_struct_Variable_1) == 0x000460, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000510, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_CustomEvent_EventTag) == 0x000514, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_CustomEvent_EventTag' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, K2Node_CustomEvent_EventData) == 0x000520, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::K2Node_CustomEvent_EventData' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0005D0, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Vector_Distance_ReturnValue) == 0x0005E8, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue_3) == 0x0005F0, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue_4) == 0x0005F8, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000600, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000608, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack, CallFunc_Multiply_DoubleDouble_ReturnValue_5) == 0x000610, "Member 'GA_Banshee_PullingAttack_C_ExecuteUbergraph_GA_Banshee_PullingAttack::CallFunc_Multiply_DoubleDouble_ReturnValue_5' has a wrong offset!");

// Function GA_Banshee_PullingAttack.GA_Banshee_PullingAttack_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Banshee_PullingAttack_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Banshee_PullingAttack_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Banshee_PullingAttack_C_K2_OnEndAbility");
static_assert(sizeof(GA_Banshee_PullingAttack_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Banshee_PullingAttack_C_K2_OnEndAbility");
static_assert(offsetof(GA_Banshee_PullingAttack_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Banshee_PullingAttack_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

