#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_CaveTroll_Attack_PunchDown

#include "Basic.hpp"

#include "GA_CaveTroll_Attack_PunchDown_classes.hpp"
#include "GA_CaveTroll_Attack_PunchDown_parameters.hpp"


namespace SDK
{

// Function GA_CaveTroll_Attack_PunchDown.GA_CaveTroll_Attack_PunchDown_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_CaveTroll_Attack_PunchDown_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_CaveTroll_Attack_PunchDown_C", "AbilityActivated");

	Params::GA_CaveTroll_Attack_PunchDown_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_CaveTroll_Attack_PunchDown.GA_CaveTroll_Attack_PunchDown_C.EventReceived_8D07916F4ACECE94208255B751735166
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_CaveTroll_Attack_PunchDown_C::EventReceived_8D07916F4ACECE94208255B751735166(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_CaveTroll_Attack_PunchDown_C", "EventReceived_8D07916F4ACECE94208255B751735166");

	Params::GA_CaveTroll_Attack_PunchDown_C_EventReceived_8D07916F4ACECE94208255B751735166 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_CaveTroll_Attack_PunchDown.GA_CaveTroll_Attack_PunchDown_C.ExecuteUbergraph_GA_CaveTroll_Attack_PunchDown
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_CaveTroll_Attack_PunchDown_C::ExecuteUbergraph_GA_CaveTroll_Attack_PunchDown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_CaveTroll_Attack_PunchDown_C", "ExecuteUbergraph_GA_CaveTroll_Attack_PunchDown");

	Params::GA_CaveTroll_Attack_PunchDown_C_ExecuteUbergraph_GA_CaveTroll_Attack_PunchDown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_CaveTroll_Attack_PunchDown.GA_CaveTroll_Attack_PunchDown_C.ServerTargetDataReceived
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     InChannelTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayEventData               EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_CaveTroll_Attack_PunchDown_C::ServerTargetDataReceived(const struct FGameplayTag& EventTag, const struct FGameplayTag& InChannelTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_CaveTroll_Attack_PunchDown_C", "ServerTargetDataReceived");

	Params::GA_CaveTroll_Attack_PunchDown_C_ServerTargetDataReceived Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.InChannelTag = std::move(InChannelTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_CaveTroll_Attack_PunchDown.GA_CaveTroll_Attack_PunchDown_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_CaveTroll_Attack_PunchDown_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_CaveTroll_Attack_PunchDown_C", "K2_OnEndAbility");

	Params::GA_CaveTroll_Attack_PunchDown_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}

}

