#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FallingIcicle_Deactivate

#include "Basic.hpp"

#include "GA_FallingIcicle_Deactivate_classes.hpp"
#include "GA_FallingIcicle_Deactivate_parameters.hpp"


namespace SDK
{

// Function GA_FallingIcicle_Deactivate.GA_FallingIcicle_Deactivate_C.ExecuteUbergraph_GA_FallingIcicle_Deactivate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_FallingIcicle_Deactivate_C::ExecuteUbergraph_GA_FallingIcicle_Deactivate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FallingIcicle_Deactivate_C", "ExecuteUbergraph_GA_FallingIcicle_Deactivate");

	Params::GA_FallingIcicle_Deactivate_C_ExecuteUbergraph_GA_FallingIcicle_Deactivate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FallingIcicle_Deactivate.GA_FallingIcicle_Deactivate_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_FallingIcicle_Deactivate_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FallingIcicle_Deactivate_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_FallingIcicle_Deactivate.GA_FallingIcicle_Deactivate_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_FallingIcicle_Deactivate_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FallingIcicle_Deactivate_C", "K2_OnEndAbility");

	Params::GA_FallingIcicle_Deactivate_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FallingIcicle_Deactivate.GA_FallingIcicle_Deactivate_C.OnFinish_5254FC8246D35460A3A593972E8F0118
// (BlueprintCallable, BlueprintEvent)

void UGA_FallingIcicle_Deactivate_C::OnFinish_5254FC8246D35460A3A593972E8F0118()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FallingIcicle_Deactivate_C", "OnFinish_5254FC8246D35460A3A593972E8F0118");

	UObject::ProcessEvent(Func, nullptr);
}

}

