#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrozenGhost_FrozenField_Deafness

#include "Basic.hpp"

#include "GA_AoeGameplayAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FrozenGhost_FrozenField_Deafness.GA_FrozenGhost_FrozenField_Deafness_C
// 0x0000 (0x0638 - 0x0638)
class UGA_FrozenGhost_FrozenField_Deafness_C final : public UGA_AoeGameplayAbilityBase_C
{
public:
	void Remove_Target_Out(bool* Param_Remove_Target_Out);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FrozenGhost_FrozenField_Deafness_C">();
	}
	static class UGA_FrozenGhost_FrozenField_Deafness_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FrozenGhost_FrozenField_Deafness_C>();
	}
};
static_assert(alignof(UGA_FrozenGhost_FrozenField_Deafness_C) == 0x000008, "Wrong alignment on UGA_FrozenGhost_FrozenField_Deafness_C");
static_assert(sizeof(UGA_FrozenGhost_FrozenField_Deafness_C) == 0x000638, "Wrong size on UGA_FrozenGhost_FrozenField_Deafness_C");

}

