#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrostDemon_BlizzardCallTimer

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GA_FrostDemon_BlizzardCallTimer.GA_FrostDemon_BlizzardCallTimer_C.AbilityActivated
// 0x00B0 (0x00B0 - 0x0000)
struct GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated final
{
public:
	struct FGameplayEventData                     TriggerEventData;                                  // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated) == 0x000008, "Wrong alignment on GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated");
static_assert(sizeof(GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated) == 0x0000B0, "Wrong size on GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated, TriggerEventData) == 0x000000, "Member 'GA_FrostDemon_BlizzardCallTimer_C_AbilityActivated::TriggerEventData' has a wrong offset!");

// Function GA_FrostDemon_BlizzardCallTimer.GA_FrostDemon_BlizzardCallTimer_C.ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer
// 0x00E8 (0x00E8 - 0x0000)
struct GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_Event_TriggerEventData;                     // 0x0008(0x00B0)(ConstParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00B8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x00C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3862[0x4];                                     // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer) == 0x000008, "Wrong alignment on GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer");
static_assert(sizeof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer) == 0x0000E8, "Wrong size on GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, EntryPoint) == 0x000000, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000004, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, K2Node_Event_TriggerEventData) == 0x000008, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::K2Node_Event_TriggerEventData' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, K2Node_CreateDelegate_OutputDelegate) == 0x0000B8, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0000C8, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_Add_IntInt_ReturnValue) == 0x0000D0, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x0000D8, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x0000E0, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer, CallFunc_Less_IntInt_ReturnValue) == 0x0000E1, "Member 'GA_FrostDemon_BlizzardCallTimer_C_ExecuteUbergraph_GA_FrostDemon_BlizzardCallTimer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

