#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrostSkeltonHalberdier_Resurrection

#include "Basic.hpp"

#include "GA_MonsterStanceChange_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FrostSkeltonHalberdier_Resurrection.GA_FrostSkeltonHalberdier_Resurrection_C
// 0x0000 (0x06B0 - 0x06B0)
class UGA_FrostSkeltonHalberdier_Resurrection_C final : public UGA_MonsterStanceChange_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FrostSkeltonHalberdier_Resurrection_C">();
	}
	static class UGA_FrostSkeltonHalberdier_Resurrection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FrostSkeltonHalberdier_Resurrection_C>();
	}
};
static_assert(alignof(UGA_FrostSkeltonHalberdier_Resurrection_C) == 0x000008, "Wrong alignment on UGA_FrostSkeltonHalberdier_Resurrection_C");
static_assert(sizeof(UGA_FrostSkeltonHalberdier_Resurrection_C) == 0x0006B0, "Wrong size on UGA_FrostSkeltonHalberdier_Resurrection_C");

}

