#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrostSentinel_ColdBlast_DealtDamage

#include "Basic.hpp"

#include "GA_AoeGameplayAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FrostSentinel_ColdBlast_DealtDamage.GA_FrostSentinel_ColdBlast_DealtDamage_C
// 0x0000 (0x0638 - 0x0638)
class UGA_FrostSentinel_ColdBlast_DealtDamage_C final : public UGA_AoeGameplayAbilityBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FrostSentinel_ColdBlast_DealtDamage_C">();
	}
	static class UGA_FrostSentinel_ColdBlast_DealtDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FrostSentinel_ColdBlast_DealtDamage_C>();
	}
};
static_assert(alignof(UGA_FrostSentinel_ColdBlast_DealtDamage_C) == 0x000008, "Wrong alignment on UGA_FrostSentinel_ColdBlast_DealtDamage_C");
static_assert(sizeof(UGA_FrostSentinel_ColdBlast_DealtDamage_C) == 0x000638, "Wrong size on UGA_FrostSentinel_ColdBlast_DealtDamage_C");

}

