#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrostSkeletonAxeman_FastReturn_Stuck

#include "Basic.hpp"

#include "DungeonCrawler_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FrostSkeletonAxeman_FastReturn_Stuck.GA_FrostSkeletonAxeman_FastReturn_Stuck_C
// 0x0000 (0x05A8 - 0x05A8)
class UGA_FrostSkeletonAxeman_FastReturn_Stuck_C final : public UGA_PlayMontageAndWaitForEvent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FrostSkeletonAxeman_FastReturn_Stuck_C">();
	}
	static class UGA_FrostSkeletonAxeman_FastReturn_Stuck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FrostSkeletonAxeman_FastReturn_Stuck_C>();
	}
};
static_assert(alignof(UGA_FrostSkeletonAxeman_FastReturn_Stuck_C) == 0x000008, "Wrong alignment on UGA_FrostSkeletonAxeman_FastReturn_Stuck_C");
static_assert(sizeof(UGA_FrostSkeletonAxeman_FastReturn_Stuck_C) == 0x0005A8, "Wrong size on UGA_FrostSkeletonAxeman_FastReturn_Stuck_C");

}

