#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FrostSkeletonFootman_Attack1_Nightmare

#include "Basic.hpp"

#include "GA_FrostSkeletonFootman_Attack1_Nightmare_classes.hpp"
#include "GA_FrostSkeletonFootman_Attack1_Nightmare_parameters.hpp"


namespace SDK
{

// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "AbilityActivated");

	Params::GA_FrostSkeletonFootman_Attack1_Nightmare_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.EventReceived_54D292B34E58D309B32DBC896734EB3B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::EventReceived_54D292B34E58D309B32DBC896734EB3B(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "EventReceived_54D292B34E58D309B32DBC896734EB3B");

	Params::GA_FrostSkeletonFootman_Attack1_Nightmare_C_EventReceived_54D292B34E58D309B32DBC896734EB3B Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.EventReceived_C7511D104C73059046A6F48340B89532
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::EventReceived_C7511D104C73059046A6F48340B89532(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "EventReceived_C7511D104C73059046A6F48340B89532");

	Params::GA_FrostSkeletonFootman_Attack1_Nightmare_C_EventReceived_C7511D104C73059046A6F48340B89532 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.ExecuteUbergraph_GA_FrostSkeletonFootman_Attack1_Nightmare
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::ExecuteUbergraph_GA_FrostSkeletonFootman_Attack1_Nightmare(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "ExecuteUbergraph_GA_FrostSkeletonFootman_Attack1_Nightmare");

	Params::GA_FrostSkeletonFootman_Attack1_Nightmare_C_ExecuteUbergraph_GA_FrostSkeletonFootman_Attack1_Nightmare Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "K2_OnEndAbility");

	Params::GA_FrostSkeletonFootman_Attack1_Nightmare_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.Set Rotation Event
// (BlueprintCallable, BlueprintEvent)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::Set_Rotation_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "Set Rotation Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.StartRotate Event
// (BlueprintCallable, BlueprintEvent)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::StartRotate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "StartRotate Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_FrostSkeletonFootman_Attack1_Nightmare.GA_FrostSkeletonFootman_Attack1_Nightmare_C.StopRotate Event
// (BlueprintCallable, BlueprintEvent)

void UGA_FrostSkeletonFootman_Attack1_Nightmare_C::StopRotate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_FrostSkeletonFootman_Attack1_Nightmare_C", "StopRotate Event");

	UObject::ProcessEvent(Func, nullptr);
}

}

