#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_GhostKing_NormalAttack_Return

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DungeonCrawler_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_GhostKing_NormalAttack_Return.GA_GhostKing_NormalAttack_Return_C
// 0x0048 (0x07A0 - 0x0758)
class UGA_GhostKing_NormalAttack_Return_C final : public UGA_MonsterChargedRangedAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_GhostKing_Common_C*                 As_BP_Ghost_King;                                  // 0x0760(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Spawn_Location;                                    // 0x0768(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Spawn_Rotation;                                    // 0x0780(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	double                                        Random_Angle;                                      // 0x0798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AbilityActivated(const struct FGameplayEventData& TriggerEventData);
	void ExecuteUbergraph_GA_GhostKing_NormalAttack_Return(int32 EntryPoint);
	void OnSuccess_5F7376234ACAB284769674B6CAA713A2(class AActor* ProjectileActor);
	void OnSuccess_FB2F52A3488E48849B6EEB88441917EB(class AActor* ProjectileActor);
	void OnSuccess_FEEF2ADC496CDFE7AE74449D038508D7(class AActor* ProjectileActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_GhostKing_NormalAttack_Return_C">();
	}
	static class UGA_GhostKing_NormalAttack_Return_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_GhostKing_NormalAttack_Return_C>();
	}
};
static_assert(alignof(UGA_GhostKing_NormalAttack_Return_C) == 0x000008, "Wrong alignment on UGA_GhostKing_NormalAttack_Return_C");
static_assert(sizeof(UGA_GhostKing_NormalAttack_Return_C) == 0x0007A0, "Wrong size on UGA_GhostKing_NormalAttack_Return_C");
static_assert(offsetof(UGA_GhostKing_NormalAttack_Return_C, UberGraphFrame) == 0x000758, "Member 'UGA_GhostKing_NormalAttack_Return_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_GhostKing_NormalAttack_Return_C, As_BP_Ghost_King) == 0x000760, "Member 'UGA_GhostKing_NormalAttack_Return_C::As_BP_Ghost_King' has a wrong offset!");
static_assert(offsetof(UGA_GhostKing_NormalAttack_Return_C, Spawn_Location) == 0x000768, "Member 'UGA_GhostKing_NormalAttack_Return_C::Spawn_Location' has a wrong offset!");
static_assert(offsetof(UGA_GhostKing_NormalAttack_Return_C, Spawn_Rotation) == 0x000780, "Member 'UGA_GhostKing_NormalAttack_Return_C::Spawn_Rotation' has a wrong offset!");
static_assert(offsetof(UGA_GhostKing_NormalAttack_Return_C, Random_Angle) == 0x000798, "Member 'UGA_GhostKing_NormalAttack_Return_C::Random_Angle' has a wrong offset!");

}

