#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HydraProjectileCollision

#include "Basic.hpp"

#include "GA_ProjectileCollision_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HydraProjectileCollision.GA_HydraProjectileCollision_C
// 0x0000 (0x05C0 - 0x05C0)
class UGA_HydraProjectileCollision_C final : public UGA_ProjectileCollision_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HydraProjectileCollision_C">();
	}
	static class UGA_HydraProjectileCollision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HydraProjectileCollision_C>();
	}
};
static_assert(alignof(UGA_HydraProjectileCollision_C) == 0x000008, "Wrong alignment on UGA_HydraProjectileCollision_C");
static_assert(sizeof(UGA_HydraProjectileCollision_C) == 0x0005C0, "Wrong size on UGA_HydraProjectileCollision_C");

}

