#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_IceGiantSpider_BackStep_Nightmare

#include "Basic.hpp"

#include "GA_IceGiantSpider_BackStep_Nightmare_classes.hpp"
#include "GA_IceGiantSpider_BackStep_Nightmare_parameters.hpp"


namespace SDK
{

// Function GA_IceGiantSpider_BackStep_Nightmare.GA_IceGiantSpider_BackStep_Nightmare_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_IceGiantSpider_BackStep_Nightmare_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGiantSpider_BackStep_Nightmare_C", "AbilityActivated");

	Params::GA_IceGiantSpider_BackStep_Nightmare_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGiantSpider_BackStep_Nightmare.GA_IceGiantSpider_BackStep_Nightmare_C.EventReceived_7CD3B9C743928CEA02A92A9BD5000D85
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_IceGiantSpider_BackStep_Nightmare_C::EventReceived_7CD3B9C743928CEA02A92A9BD5000D85(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGiantSpider_BackStep_Nightmare_C", "EventReceived_7CD3B9C743928CEA02A92A9BD5000D85");

	Params::GA_IceGiantSpider_BackStep_Nightmare_C_EventReceived_7CD3B9C743928CEA02A92A9BD5000D85 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGiantSpider_BackStep_Nightmare.GA_IceGiantSpider_BackStep_Nightmare_C.ExecuteUbergraph_GA_IceGiantSpider_BackStep_Nightmare
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_IceGiantSpider_BackStep_Nightmare_C::ExecuteUbergraph_GA_IceGiantSpider_BackStep_Nightmare(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGiantSpider_BackStep_Nightmare_C", "ExecuteUbergraph_GA_IceGiantSpider_BackStep_Nightmare");

	Params::GA_IceGiantSpider_BackStep_Nightmare_C_ExecuteUbergraph_GA_IceGiantSpider_BackStep_Nightmare Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGiantSpider_BackStep_Nightmare.GA_IceGiantSpider_BackStep_Nightmare_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_IceGiantSpider_BackStep_Nightmare_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGiantSpider_BackStep_Nightmare_C", "K2_OnEndAbility");

	Params::GA_IceGiantSpider_BackStep_Nightmare_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}

}

