#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_IceGolem_Attack_Combo2

#include "Basic.hpp"

#include "GA_IceGolem_Attack_Combo2_classes.hpp"
#include "GA_IceGolem_Attack_Combo2_parameters.hpp"


namespace SDK
{

// Function GA_IceGolem_Attack_Combo2.GA_IceGolem_Attack_Combo2_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_IceGolem_Attack_Combo2_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGolem_Attack_Combo2_C", "AbilityActivated");

	Params::GA_IceGolem_Attack_Combo2_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGolem_Attack_Combo2.GA_IceGolem_Attack_Combo2_C.EventReceived_39CE64674FEBEF0820E02FA9AE643C62
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_IceGolem_Attack_Combo2_C::EventReceived_39CE64674FEBEF0820E02FA9AE643C62(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGolem_Attack_Combo2_C", "EventReceived_39CE64674FEBEF0820E02FA9AE643C62");

	Params::GA_IceGolem_Attack_Combo2_C_EventReceived_39CE64674FEBEF0820E02FA9AE643C62 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGolem_Attack_Combo2.GA_IceGolem_Attack_Combo2_C.ExecuteUbergraph_GA_IceGolem_Attack_Combo2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_IceGolem_Attack_Combo2_C::ExecuteUbergraph_GA_IceGolem_Attack_Combo2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGolem_Attack_Combo2_C", "ExecuteUbergraph_GA_IceGolem_Attack_Combo2");

	Params::GA_IceGolem_Attack_Combo2_C_ExecuteUbergraph_GA_IceGolem_Attack_Combo2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_IceGolem_Attack_Combo2.GA_IceGolem_Attack_Combo2_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_IceGolem_Attack_Combo2_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_IceGolem_Attack_Combo2_C", "K2_OnEndAbility");

	Params::GA_IceGolem_Attack_Combo2_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}

}

