#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Kindness

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "DungeonCrawler_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_Kindness.GA_Kindness_C.EventReceived_89CB85084463471F9396E38CC9E180E6
// 0x00B0 (0x00B0 - 0x0000)
struct GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6 final
{
public:
	struct FGameplayEventData                     Payload;                                           // 0x0000(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6) == 0x000008, "Wrong alignment on GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6");
static_assert(sizeof(GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6) == 0x0000B0, "Wrong size on GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6");
static_assert(offsetof(GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6, Payload) == 0x000000, "Member 'GA_Kindness_C_EventReceived_89CB85084463471F9396E38CC9E180E6::Payload' has a wrong offset!");

// Function GA_Kindness.GA_Kindness_C.ExecuteUbergraph_GA_Kindness
// 0x0320 (0x0320 - 0x0000)
struct GA_Kindness_C_ExecuteUbergraph_GA_Kindness final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPrimaryAssetId                        CallFunc_GetPrimaryAssetIdFromObject_ReturnValue;  // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetConstantFloat_ReturnValue;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FGameplayEventData& Payload)> K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_CustomEvent_Payload;                        // 0x0028(0x00B0)()
	struct FGameplayEventData                     Temp_struct_Variable;                              // 0x00D8(0x00B0)()
	class UAbilityTask_WaitGameplayEvent*         CallFunc_WaitGameplayEvent_ReturnValue;            // 0x0188(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55CE[0x7];                                     // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55CF[0x3];                                     // 0x01A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDCGameplayEffectSetByCallerData       K2Node_MakeStruct_DCGameplayEffectSetByCallerData; // 0x01A4(0x000C)(NoDestructor)
	TArray<struct FDCGameplayEffectSetByCallerData> K2Node_MakeArray_Array;                            // 0x01B0(0x0010)(ReferenceParm)
	struct FDCGameplayEffectData                  K2Node_MakeStruct_DCGameplayEffectData;            // 0x01C0(0x0068)()
	struct FGameplayEventData                     K2Node_Event_EventData;                            // 0x0228(0x00B0)(ConstParm)
	TArray<struct FDCGameplayEffectData>          K2Node_MakeArray_Array_1;                          // 0x02D8(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55D0[0x7];                                     // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x02F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FActiveGameplayEffectHandle>    CallFunc_ApplyGameplayEffects_ReturnValue;         // 0x02F8(0x0010)(ReferenceParm)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_SetByCallerValue_ImplicitCast;   // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness) == 0x000008, "Wrong alignment on GA_Kindness_C_ExecuteUbergraph_GA_Kindness");
static_assert(sizeof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness) == 0x000320, "Wrong size on GA_Kindness_C_ExecuteUbergraph_GA_Kindness");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, EntryPoint) == 0x000000, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_GetPrimaryAssetIdFromObject_ReturnValue) == 0x000004, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_GetPrimaryAssetIdFromObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_GetConstantFloat_ReturnValue) == 0x000014, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_GetConstantFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_CustomEvent_Payload) == 0x000028, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_CustomEvent_Payload' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, Temp_struct_Variable) == 0x0000D8, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_WaitGameplayEvent_ReturnValue) == 0x000188, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_WaitGameplayEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_IsValid_ReturnValue) == 0x000190, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000198, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0001A0, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_MakeStruct_DCGameplayEffectSetByCallerData) == 0x0001A4, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_MakeStruct_DCGameplayEffectSetByCallerData' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_MakeArray_Array) == 0x0001B0, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_MakeStruct_DCGameplayEffectData) == 0x0001C0, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_MakeStruct_DCGameplayEffectData' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_Event_EventData) == 0x000228, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_Event_EventData' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_MakeArray_Array_1) == 0x0002D8, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_IsLocallyControlled_ReturnValue) == 0x0002E8, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x0002F0, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_ApplyGameplayEffects_ReturnValue) == 0x0002F8, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_ApplyGameplayEffects_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x000308, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000310, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Kindness_C_ExecuteUbergraph_GA_Kindness, K2Node_MakeStruct_SetByCallerValue_ImplicitCast) == 0x000318, "Member 'GA_Kindness_C_ExecuteUbergraph_GA_Kindness::K2Node_MakeStruct_SetByCallerValue_ImplicitCast' has a wrong offset!");

// Function GA_Kindness.GA_Kindness_C.K2_ActivateAbilityFromEvent
// 0x00B0 (0x00B0 - 0x0000)
struct GA_Kindness_C_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(GA_Kindness_C_K2_ActivateAbilityFromEvent) == 0x000008, "Wrong alignment on GA_Kindness_C_K2_ActivateAbilityFromEvent");
static_assert(sizeof(GA_Kindness_C_K2_ActivateAbilityFromEvent) == 0x0000B0, "Wrong size on GA_Kindness_C_K2_ActivateAbilityFromEvent");
static_assert(offsetof(GA_Kindness_C_K2_ActivateAbilityFromEvent, EventData) == 0x000000, "Member 'GA_Kindness_C_K2_ActivateAbilityFromEvent::EventData' has a wrong offset!");

}

