#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_LichNormalAttack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DungeonCrawler_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_LichNormalAttack.GA_LichNormalAttack_C
// 0x0008 (0x0760 - 0x0758)
class UGA_LichNormalAttack_C final : public UGA_MonsterChargedRangedAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AbilityActivated(const struct FGameplayEventData& TriggerEventData);
	void EventReceived_3D96C36F4FAC76511505409F6321DC9E(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData);
	void ExecuteUbergraph_GA_LichNormalAttack(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_LichNormalAttack_C">();
	}
	static class UGA_LichNormalAttack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_LichNormalAttack_C>();
	}
};
static_assert(alignof(UGA_LichNormalAttack_C) == 0x000008, "Wrong alignment on UGA_LichNormalAttack_C");
static_assert(sizeof(UGA_LichNormalAttack_C) == 0x000760, "Wrong size on UGA_LichNormalAttack_C");
static_assert(offsetof(UGA_LichNormalAttack_C, UberGraphFrame) == 0x000758, "Member 'UGA_LichNormalAttack_C::UberGraphFrame' has a wrong offset!");

}

