#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NaturesTouch

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_SpellCasting_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NaturesTouch.GA_NaturesTouch_C
// 0x0008 (0x0670 - 0x0668)
class UGA_NaturesTouch_C final : public UGA_SpellCasting_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0668(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AbilityActivated_BP(const struct FGameplayEventData& TriggerEventData, bool bIsSocketSightBlocked);
	void Cancelled_AA31A4724F0A658EA8CBC3B591A33194(const struct FGameplayAbilityTargetDataHandle& Data);
	void ExecuteUbergraph_GA_NaturesTouch(int32 EntryPoint);
	void ValidData_AA31A4724F0A658EA8CBC3B591A33194(const struct FGameplayAbilityTargetDataHandle& Data);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_NaturesTouch_C">();
	}
	static class UGA_NaturesTouch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NaturesTouch_C>();
	}
};
static_assert(alignof(UGA_NaturesTouch_C) == 0x000008, "Wrong alignment on UGA_NaturesTouch_C");
static_assert(sizeof(UGA_NaturesTouch_C) == 0x000670, "Wrong size on UGA_NaturesTouch_C");
static_assert(offsetof(UGA_NaturesTouch_C, UberGraphFrame) == 0x000668, "Member 'UGA_NaturesTouch_C::UberGraphFrame' has a wrong offset!");

}

