#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NaturalHealingGranted

#include "Basic.hpp"

#include "GA_PerkGranted_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NaturalHealingGranted.GA_NaturalHealingGranted_C
// 0x0018 (0x05E0 - 0x05C8)
class UGA_NaturalHealingGranted_C final : public UGA_PerkGranted_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_NaturalHealingGranted_C;         // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<struct FPrimaryAssetId>                NaturalHealingAssetId;                             // 0x05D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_NaturalHealingGranted(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnFinished_2F3585534FB4E24544F34880F202DD5F(int32 ActionNumber);
	void OnPerformAction_2F3585534FB4E24544F34880F202DD5F(int32 ActionNumber);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_NaturalHealingGranted_C">();
	}
	static class UGA_NaturalHealingGranted_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NaturalHealingGranted_C>();
	}
};
static_assert(alignof(UGA_NaturalHealingGranted_C) == 0x000008, "Wrong alignment on UGA_NaturalHealingGranted_C");
static_assert(sizeof(UGA_NaturalHealingGranted_C) == 0x0005E0, "Wrong size on UGA_NaturalHealingGranted_C");
static_assert(offsetof(UGA_NaturalHealingGranted_C, UberGraphFrame_GA_NaturalHealingGranted_C) == 0x0005C8, "Member 'UGA_NaturalHealingGranted_C::UberGraphFrame_GA_NaturalHealingGranted_C' has a wrong offset!");
static_assert(offsetof(UGA_NaturalHealingGranted_C, NaturalHealingAssetId) == 0x0005D0, "Member 'UGA_NaturalHealingGranted_C::NaturalHealingAssetId' has a wrong offset!");

}

