#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Otto_Lie_To_Sit

#include "Basic.hpp"

#include "GA_Otto_Lie_To_Sit_classes.hpp"
#include "GA_Otto_Lie_To_Sit_parameters.hpp"


namespace SDK
{

// Function GA_Otto_Lie_To_Sit.GA_Otto_Lie_To_Sit_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Otto_Lie_To_Sit_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Otto_Lie_To_Sit_C", "AbilityActivated");

	Params::GA_Otto_Lie_To_Sit_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Otto_Lie_To_Sit.GA_Otto_Lie_To_Sit_C.ExecuteUbergraph_GA_Otto_Lie_To_Sit
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Otto_Lie_To_Sit_C::ExecuteUbergraph_GA_Otto_Lie_To_Sit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Otto_Lie_To_Sit_C", "ExecuteUbergraph_GA_Otto_Lie_To_Sit");

	Params::GA_Otto_Lie_To_Sit_C_ExecuteUbergraph_GA_Otto_Lie_To_Sit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

