#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_PickUp

#include "Basic.hpp"

#include "DungeonCrawler_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_PickUp.GA_PickUp_C
// 0x0000 (0x0708 - 0x0708)
class UGA_PickUp_C final : public UGA_PickUp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_PickUp_C">();
	}
	static class UGA_PickUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_PickUp_C>();
	}
};
static_assert(alignof(UGA_PickUp_C) == 0x000008, "Wrong alignment on UGA_PickUp_C");
static_assert(sizeof(UGA_PickUp_C) == 0x000708, "Wrong size on UGA_PickUp_C");

}

