#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_RuinsGolem_AttackSlam

#include "Basic.hpp"

#include "GA_RuinsGolem_AttackSlam_classes.hpp"
#include "GA_RuinsGolem_AttackSlam_parameters.hpp"


namespace SDK
{

// Function GA_RuinsGolem_AttackSlam.GA_RuinsGolem_AttackSlam_C.AbilityActivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               TriggerEventData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_RuinsGolem_AttackSlam_C::AbilityActivated(const struct FGameplayEventData& TriggerEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RuinsGolem_AttackSlam_C", "AbilityActivated");

	Params::GA_RuinsGolem_AttackSlam_C_AbilityActivated Parms{};

	Parms.TriggerEventData = std::move(TriggerEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RuinsGolem_AttackSlam.GA_RuinsGolem_AttackSlam_C.EventReceived_9F0B47BF4D356B3DCEF1B9ABE7B467F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_RuinsGolem_AttackSlam_C::EventReceived_9F0B47BF4D356B3DCEF1B9ABE7B467F6(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RuinsGolem_AttackSlam_C", "EventReceived_9F0B47BF4D356B3DCEF1B9ABE7B467F6");

	Params::GA_RuinsGolem_AttackSlam_C_EventReceived_9F0B47BF4D356B3DCEF1B9ABE7B467F6 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RuinsGolem_AttackSlam.GA_RuinsGolem_AttackSlam_C.ExecuteUbergraph_GA_RuinsGolem_AttackSlam
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RuinsGolem_AttackSlam_C::ExecuteUbergraph_GA_RuinsGolem_AttackSlam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RuinsGolem_AttackSlam_C", "ExecuteUbergraph_GA_RuinsGolem_AttackSlam");

	Params::GA_RuinsGolem_AttackSlam_C_ExecuteUbergraph_GA_RuinsGolem_AttackSlam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RuinsGolem_AttackSlam.GA_RuinsGolem_AttackSlam_C.Spawn Aoe
// (BlueprintCallable, BlueprintEvent)

void UGA_RuinsGolem_AttackSlam_C::Spawn_Aoe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RuinsGolem_AttackSlam_C", "Spawn Aoe");

	UObject::ProcessEvent(Func, nullptr);
}

}

