#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SkeletonGuardmanSummoned_FakeDeath

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_PlayMontageAndWaitForEventBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_SkeletonGuardmanSummoned_FakeDeath.GA_SkeletonGuardmanSummoned_FakeDeath_C
// 0x0008 (0x0680 - 0x0678)
class UGA_SkeletonGuardmanSummoned_FakeDeath_C final : public UGA_PlayMontageAndWaitForEventBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_SkeletonGuardmanSummoned_FakeDeath_C; // 0x0678(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AbilityActivated(const struct FGameplayEventData& TriggerEventData);
	void ExecuteUbergraph_GA_SkeletonGuardmanSummoned_FakeDeath(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_SkeletonGuardmanSummoned_FakeDeath_C">();
	}
	static class UGA_SkeletonGuardmanSummoned_FakeDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_SkeletonGuardmanSummoned_FakeDeath_C>();
	}
};
static_assert(alignof(UGA_SkeletonGuardmanSummoned_FakeDeath_C) == 0x000008, "Wrong alignment on UGA_SkeletonGuardmanSummoned_FakeDeath_C");
static_assert(sizeof(UGA_SkeletonGuardmanSummoned_FakeDeath_C) == 0x000680, "Wrong size on UGA_SkeletonGuardmanSummoned_FakeDeath_C");
static_assert(offsetof(UGA_SkeletonGuardmanSummoned_FakeDeath_C, UberGraphFrame_GA_SkeletonGuardmanSummoned_FakeDeath_C) == 0x000678, "Member 'UGA_SkeletonGuardmanSummoned_FakeDeath_C::UberGraphFrame_GA_SkeletonGuardmanSummoned_FakeDeath_C' has a wrong offset!");

}

