#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SkeletonAxeman_Attack1

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_SkeletonAxeman_Attack1.GA_SkeletonAxeman_Attack1_C.AbilityActivated
// 0x00B0 (0x00B0 - 0x0000)
struct GA_SkeletonAxeman_Attack1_C_AbilityActivated final
{
public:
	struct FGameplayEventData                     TriggerEventData;                                  // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_SkeletonAxeman_Attack1_C_AbilityActivated) == 0x000008, "Wrong alignment on GA_SkeletonAxeman_Attack1_C_AbilityActivated");
static_assert(sizeof(GA_SkeletonAxeman_Attack1_C_AbilityActivated) == 0x0000B0, "Wrong size on GA_SkeletonAxeman_Attack1_C_AbilityActivated");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_AbilityActivated, TriggerEventData) == 0x000000, "Member 'GA_SkeletonAxeman_Attack1_C_AbilityActivated::TriggerEventData' has a wrong offset!");

// Function GA_SkeletonAxeman_Attack1.GA_SkeletonAxeman_Attack1_C.EventReceived_14666380446D55B58D0721B32C91ABD3
// 0x00B0 (0x00B0 - 0x0000)
struct GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3 final
{
public:
	struct FGameplayEventData                     Payload;                                           // 0x0000(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3) == 0x000008, "Wrong alignment on GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3");
static_assert(sizeof(GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3) == 0x0000B0, "Wrong size on GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3, Payload) == 0x000000, "Member 'GA_SkeletonAxeman_Attack1_C_EventReceived_14666380446D55B58D0721B32C91ABD3::Payload' has a wrong offset!");

// Function GA_SkeletonAxeman_Attack1.GA_SkeletonAxeman_Attack1_C.EventReceived_46D29C724C0705ED9484D1BA19D06997
// 0x00B0 (0x00B0 - 0x0000)
struct GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997 final
{
public:
	struct FGameplayEventData                     Payload;                                           // 0x0000(0x00B0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997) == 0x000008, "Wrong alignment on GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997");
static_assert(sizeof(GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997) == 0x0000B0, "Wrong size on GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997, Payload) == 0x000000, "Member 'GA_SkeletonAxeman_Attack1_C_EventReceived_46D29C724C0705ED9484D1BA19D06997::Payload' has a wrong offset!");

// Function GA_SkeletonAxeman_Attack1.GA_SkeletonAxeman_Attack1_C.ExecuteUbergraph_GA_SkeletonAxeman_Attack1
// 0x0408 (0x0408 - 0x0000)
struct GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5245[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     Temp_struct_Variable;                              // 0x0008(0x00B0)()
	class UAbilityTask_WaitGameplayEvent*         CallFunc_WaitGameplayEvent_ReturnValue;            // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FGameplayEventData& Payload)> K2Node_CreateDelegate_OutputDelegate;              // 0x00C0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5246[0x7];                                     // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_CustomEvent_Payload;                        // 0x00D8(0x00B0)()
	struct FGameplayEventData                     Temp_struct_Variable_1;                            // 0x0188(0x00B0)()
	class UAbilityTask_WaitGameplayEvent*         CallFunc_WaitGameplayEvent_ReturnValue_1;          // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5247[0x7];                                     // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_CustomEvent_Payload_1;                      // 0x0248(0x00B0)()
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5248[0x3];                                     // 0x0301(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FGameplayEventData& Payload)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0304(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5249[0x4];                                     // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_Event_TriggerEventData;                     // 0x0318(0x00B0)(ConstParm)
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x03C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_SkeletonAxeman_C*                   K2Node_DynamicCast_AsBP_Skeleton_Axeman;           // 0x03D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x03D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckGradeType_ReturnValue;               // 0x03D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524A[0x6];                                     // 0x03DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1; // 0x03E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_Result; // 0x03E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524B[0x7];                                     // 0x03E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ADCCharacterBase*>               CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_DCCharacterBase; // 0x03F0(0x0010)(ReferenceParm)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0400(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0401(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1) == 0x000008, "Wrong alignment on GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1");
static_assert(sizeof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1) == 0x000408, "Wrong size on GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, EntryPoint) == 0x000000, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, Temp_struct_Variable) == 0x000008, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_WaitGameplayEvent_ReturnValue) == 0x0000B8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_WaitGameplayEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_CreateDelegate_OutputDelegate) == 0x0000C0, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_IsValid_ReturnValue) == 0x0000D0, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_CustomEvent_Payload) == 0x0000D8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_CustomEvent_Payload' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, Temp_struct_Variable_1) == 0x000188, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_WaitGameplayEvent_ReturnValue_1) == 0x000238, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_WaitGameplayEvent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_IsValid_ReturnValue_1) == 0x000240, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_CustomEvent_Payload_1) == 0x000248, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_CustomEvent_Payload_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_RandomFloatInRange_ReturnValue) == 0x0002F8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000300, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_CreateDelegate_OutputDelegate_1) == 0x000304, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_Event_TriggerEventData) == 0x000318, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_Event_TriggerEventData' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x0003C8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_DynamicCast_AsBP_Skeleton_Axeman) == 0x0003D0, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_DynamicCast_AsBP_Skeleton_Axeman' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, K2Node_DynamicCast_bSuccess) == 0x0003D8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_CheckGradeType_ReturnValue) == 0x0003D9, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_CheckGradeType_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1) == 0x0003E0, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_GetAvatarActorFromActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_Result) == 0x0003E8, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_Result' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_DCCharacterBase) == 0x0003F0, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_Get_Enemies_In_Range_And_Angle_From_Actor_DCCharacterBase' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000400, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1, CallFunc_BooleanOR_ReturnValue) == 0x000401, "Member 'GA_SkeletonAxeman_Attack1_C_ExecuteUbergraph_GA_SkeletonAxeman_Attack1::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

