#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Sabertooth_Attack_Phase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DungeonCrawler_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Sabertooth_Attack_Phase.GA_Sabertooth_Attack_Phase_C
// 0x0008 (0x05B0 - 0x05A8)
class UGA_Sabertooth_Attack_Phase_C final : public UDCMonsterGameplayAbilityBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AbilityActivated(const struct FGameplayEventData& TriggerEventData);
	void EventReceived_043445024B5E58937276D09AD3F0794E(const struct FGameplayEventData& Payload);
	void ExecuteUbergraph_GA_Sabertooth_Attack_Phase(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Sabertooth_Attack_Phase_C">();
	}
	static class UGA_Sabertooth_Attack_Phase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Sabertooth_Attack_Phase_C>();
	}
};
static_assert(alignof(UGA_Sabertooth_Attack_Phase_C) == 0x000008, "Wrong alignment on UGA_Sabertooth_Attack_Phase_C");
static_assert(sizeof(UGA_Sabertooth_Attack_Phase_C) == 0x0005B0, "Wrong size on UGA_Sabertooth_Attack_Phase_C");
static_assert(offsetof(UGA_Sabertooth_Attack_Phase_C, UberGraphFrame) == 0x0005A8, "Member 'UGA_Sabertooth_Attack_Phase_C::UberGraphFrame' has a wrong offset!");

}

