#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SkeletonSpearman_Attack1

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_SkeletonSpearman_Attack1.GA_SkeletonSpearman_Attack1_C.ExecuteUbergraph_GA_SkeletonSpearman_Attack1
// 0x0008 (0x0008 - 0x0000)
struct GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1) == 0x000004, "Wrong alignment on GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1");
static_assert(sizeof(GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1) == 0x000008, "Wrong size on GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1");
static_assert(offsetof(GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1, EntryPoint) == 0x000000, "Member 'GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1, K2Node_Event_bWasCancelled) == 0x000004, "Member 'GA_SkeletonSpearman_Attack1_C_ExecuteUbergraph_GA_SkeletonSpearman_Attack1::K2Node_Event_bWasCancelled' has a wrong offset!");

// Function GA_SkeletonSpearman_Attack1.GA_SkeletonSpearman_Attack1_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility");
static_assert(sizeof(GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility");
static_assert(offsetof(GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_SkeletonSpearman_Attack1_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

