#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SkeletonWarlord_Order_ThrowingKnives

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_PlayMontageAndWaitForEventBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_SkeletonWarlord_Order_ThrowingKnives.GA_SkeletonWarlord_Order_ThrowingKnives_C
// 0x0008 (0x0680 - 0x0678)
class UGA_SkeletonWarlord_Order_ThrowingKnives_C final : public UGA_PlayMontageAndWaitForEventBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_SkeletonWarlord_Order_ThrowingKnives_C; // 0x0678(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AbilityActivated(const struct FGameplayEventData& TriggerEventData);
	void EventReceived_4779E9A8467D8891C1C2CDBF27B92EC1(const struct FGameplayEventData& Payload);
	void ExecuteUbergraph_GA_SkeletonWarlord_Order_ThrowingKnives(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_SkeletonWarlord_Order_ThrowingKnives_C">();
	}
	static class UGA_SkeletonWarlord_Order_ThrowingKnives_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_SkeletonWarlord_Order_ThrowingKnives_C>();
	}
};
static_assert(alignof(UGA_SkeletonWarlord_Order_ThrowingKnives_C) == 0x000008, "Wrong alignment on UGA_SkeletonWarlord_Order_ThrowingKnives_C");
static_assert(sizeof(UGA_SkeletonWarlord_Order_ThrowingKnives_C) == 0x000680, "Wrong size on UGA_SkeletonWarlord_Order_ThrowingKnives_C");
static_assert(offsetof(UGA_SkeletonWarlord_Order_ThrowingKnives_C, UberGraphFrame_GA_SkeletonWarlord_Order_ThrowingKnives_C) == 0x000678, "Member 'UGA_SkeletonWarlord_Order_ThrowingKnives_C::UberGraphFrame_GA_SkeletonWarlord_Order_ThrowingKnives_C' has a wrong offset!");

}

