#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SpiderWebDeactivate

#include "Basic.hpp"

#include "GA_SpiderWebDeactivate_classes.hpp"
#include "GA_SpiderWebDeactivate_parameters.hpp"


namespace SDK
{

// Function GA_SpiderWebDeactivate.GA_SpiderWebDeactivate_C.ExecuteUbergraph_GA_SpiderWebDeactivate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SpiderWebDeactivate_C::ExecuteUbergraph_GA_SpiderWebDeactivate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SpiderWebDeactivate_C", "ExecuteUbergraph_GA_SpiderWebDeactivate");

	Params::GA_SpiderWebDeactivate_C_ExecuteUbergraph_GA_SpiderWebDeactivate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SpiderWebDeactivate.GA_SpiderWebDeactivate_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_SpiderWebDeactivate_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SpiderWebDeactivate_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SpiderWebDeactivate.GA_SpiderWebDeactivate_C.OnFinish_A5712FA946A02343815E6CB60CEC09F5
// (BlueprintCallable, BlueprintEvent)

void UGA_SpiderWebDeactivate_C::OnFinish_A5712FA946A02343815E6CB60CEC09F5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SpiderWebDeactivate_C", "OnFinish_A5712FA946A02343815E6CB60CEC09F5");

	UObject::ProcessEvent(Func, nullptr);
}

}

