#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TreeOfLife

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_TreeOfLife.GA_TreeOfLife_C.AbilityActivated_BP
// 0x00B8 (0x00B8 - 0x0000)
struct GA_TreeOfLife_C_AbilityActivated_BP final
{
public:
	struct FGameplayEventData                     TriggerEventData;                                  // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          bIsSocketSightBlocked;                             // 0x00B0(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_TreeOfLife_C_AbilityActivated_BP) == 0x000008, "Wrong alignment on GA_TreeOfLife_C_AbilityActivated_BP");
static_assert(sizeof(GA_TreeOfLife_C_AbilityActivated_BP) == 0x0000B8, "Wrong size on GA_TreeOfLife_C_AbilityActivated_BP");
static_assert(offsetof(GA_TreeOfLife_C_AbilityActivated_BP, TriggerEventData) == 0x000000, "Member 'GA_TreeOfLife_C_AbilityActivated_BP::TriggerEventData' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_AbilityActivated_BP, bIsSocketSightBlocked) == 0x0000B0, "Member 'GA_TreeOfLife_C_AbilityActivated_BP::bIsSocketSightBlocked' has a wrong offset!");

// Function GA_TreeOfLife.GA_TreeOfLife_C.Cancelled_D524F13046661C579D01BFBAD505225F
// 0x0028 (0x0028 - 0x0000)
struct GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F) == 0x000008, "Wrong alignment on GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F");
static_assert(sizeof(GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F) == 0x000028, "Wrong size on GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F");
static_assert(offsetof(GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F, Data) == 0x000000, "Member 'GA_TreeOfLife_C_Cancelled_D524F13046661C579D01BFBAD505225F::Data' has a wrong offset!");

// Function GA_TreeOfLife.GA_TreeOfLife_C.ExecuteUbergraph_GA_TreeOfLife
// 0x0360 (0x0360 - 0x0000)
struct GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A3[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_Event_TriggerEventData;                     // 0x0008(0x00B0)(ConstParm)
	bool                                          K2Node_Event_bIsSocketSightBlocked;                // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A4[0x3];                                     // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate;              // 0x00BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A5[0x4];                                     // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data_1;                         // 0x00D0(0x0028)(ConstParm)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data;                           // 0x00F8(0x0028)(ConstParm)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0120(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable;                              // 0x0130(0x0028)()
	class UAbilityTask_WaitTargetData*            CallFunc_WaitTargetData_ReturnValue;               // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A6[0x7];                                     // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameplayAbilityTargetActor*            CallFunc_BeginSpawningActor_SpawnedActor;          // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BeginSpawningActor_ReturnValue;           // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A7[0x6];                                     // 0x0172(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_GetHitResultFromTargetData_ReturnValue;   // 0x0178(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_CastToTarget_ReturnValue;                 // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0261(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0262(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A8[0x1];                                     // 0x0263(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58A9[0x4];                                     // 0x026C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0270(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0288(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x02A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x02B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x02D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x02D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x02E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x02FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58AA[0x4];                                     // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0308(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0320(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAimRadius_ReturnValue;                 // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x033C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58AB[0x3];                                     // 0x033D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             K2Node_DynamicCast_As___;                          // 0x0340(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58AC[0x3];                                     // 0x0349(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRange_ReturnValue;                     // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SetDoublePropertyByName_Value_ImplicitCast; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1; // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife) == 0x000008, "Wrong alignment on GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife");
static_assert(sizeof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife) == 0x000360, "Wrong size on GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, EntryPoint) == 0x000000, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_Event_TriggerEventData) == 0x000008, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_Event_TriggerEventData' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_Event_bIsSocketSightBlocked) == 0x0000B8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_Event_bIsSocketSightBlocked' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_CreateDelegate_OutputDelegate) == 0x0000BC, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_CustomEvent_Data_1) == 0x0000D0, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_CustomEvent_Data_1' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_CustomEvent_Data) == 0x0000F8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_CustomEvent_Data' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_CreateDelegate_OutputDelegate_1) == 0x000120, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, Temp_struct_Variable) == 0x000130, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_WaitTargetData_ReturnValue) == 0x000158, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_WaitTargetData_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_IsValid_ReturnValue) == 0x000160, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BeginSpawningActor_SpawnedActor) == 0x000168, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BeginSpawningActor_SpawnedActor' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BeginSpawningActor_ReturnValue) == 0x000170, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BeginSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_IsValid_ReturnValue_1) == 0x000171, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_GetHitResultFromTargetData_ReturnValue) == 0x000178, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_GetHitResultFromTargetData_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_CastToTarget_ReturnValue) == 0x000260, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_CastToTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_bBlockingHit) == 0x000261, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_bInitialOverlap) == 0x000262, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_Time) == 0x000264, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_Distance) == 0x000268, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_Location) == 0x000270, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_ImpactPoint) == 0x000288, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_Normal) == 0x0002A0, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_ImpactNormal) == 0x0002B8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_PhysMat) == 0x0002D0, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_HitActor) == 0x0002D8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_HitComponent) == 0x0002E0, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_HitBoneName) == 0x0002E8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_BoneName) == 0x0002F0, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_HitItem) == 0x0002F8, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_ElementIndex) == 0x0002FC, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_FaceIndex) == 0x000300, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_TraceStart) == 0x000308, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_BreakHitResult_TraceEnd) == 0x000320, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_GetAimRadius_ReturnValue) == 0x000338, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_GetAimRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_IsValid_ReturnValue_2) == 0x00033C, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_DynamicCast_As___) == 0x000340, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_DynamicCast_As___' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, K2Node_DynamicCast_bSuccess) == 0x000348, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_GetRange_ReturnValue) == 0x00034C, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_GetRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_SetDoublePropertyByName_Value_ImplicitCast) == 0x000350, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_SetDoublePropertyByName_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife, CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1) == 0x000358, "Member 'GA_TreeOfLife_C_ExecuteUbergraph_GA_TreeOfLife::CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1' has a wrong offset!");

// Function GA_TreeOfLife.GA_TreeOfLife_C.ValidData_D524F13046661C579D01BFBAD505225F
// 0x0028 (0x0028 - 0x0000)
struct GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F) == 0x000008, "Wrong alignment on GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F");
static_assert(sizeof(GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F) == 0x000028, "Wrong size on GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F");
static_assert(offsetof(GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F, Data) == 0x000000, "Member 'GA_TreeOfLife_C_ValidData_D524F13046661C579D01BFBAD505225F::Data' has a wrong offset!");

}

