#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Antimagic

#include "Basic.hpp"

#include "GE_Inf_AllMagicalReduction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Antimagic.GE_Antimagic_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Antimagic_C final : public UGE_Inf_AllMagicalReduction_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Antimagic_C">();
	}
	static class UGE_Antimagic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Antimagic_C>();
	}
};
static_assert(alignof(UGE_Antimagic_C) == 0x000008, "Wrong alignment on UGE_Antimagic_C");
static_assert(sizeof(UGE_Antimagic_C) == 0x000A70, "Wrong size on UGE_Antimagic_C");

}

