#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_AchillesStrike_HitSlow

#include "Basic.hpp"

#include "GE_Dur_MoveSpeedModReduce_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_AchillesStrike_HitSlow.GE_AchillesStrike_HitSlow_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_AchillesStrike_HitSlow_C final : public UGE_Dur_MoveSpeedModReduce_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_AchillesStrike_HitSlow_C">();
	}
	static class UGE_AchillesStrike_HitSlow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_AchillesStrike_HitSlow_C>();
	}
};
static_assert(alignof(UGE_AchillesStrike_HitSlow_C) == 0x000008, "Wrong alignment on UGE_AchillesStrike_HitSlow_C");
static_assert(sizeof(UGE_AchillesStrike_HitSlow_C) == 0x000A70, "Wrong size on UGE_AchillesStrike_HitSlow_C");

}

