#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_CharacterSkinMummy

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_CharacterSkinMummy.GE_CharacterSkinMummy_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_CharacterSkinMummy_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_CharacterSkinMummy_C">();
	}
	static class UGE_CharacterSkinMummy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_CharacterSkinMummy_C>();
	}
};
static_assert(alignof(UGE_CharacterSkinMummy_C) == 0x000008, "Wrong alignment on UGE_CharacterSkinMummy_C");
static_assert(sizeof(UGE_CharacterSkinMummy_C) == 0x000A70, "Wrong size on UGE_CharacterSkinMummy_C");

}

