#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_StealthSteps

#include "Basic.hpp"

#include "GE_Inf_MoveSpeedAdd_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_StealthSteps.GE_StealthSteps_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_StealthSteps_C final : public UGE_Inf_MoveSpeedAdd_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_StealthSteps_C">();
	}
	static class UGE_StealthSteps_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_StealthSteps_C>();
	}
};
static_assert(alignof(UGE_StealthSteps_C) == 0x000008, "Wrong alignment on UGE_StealthSteps_C");
static_assert(sizeof(UGE_StealthSteps_C) == 0x000A70, "Wrong size on UGE_StealthSteps_C");

}

