#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SlayerBuff

#include "Basic.hpp"

#include "GE_Inf_PhysicalDamageWeapon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SlayerBuff.GE_SlayerBuff_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_SlayerBuff_C final : public UGE_Inf_PhysicalDamageWeapon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SlayerBuff_C">();
	}
	static class UGE_SlayerBuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SlayerBuff_C>();
	}
};
static_assert(alignof(UGE_SlayerBuff_C) == 0x000008, "Wrong alignment on UGE_SlayerBuff_C");
static_assert(sizeof(UGE_SlayerBuff_C) == 0x000A70, "Wrong size on UGE_SlayerBuff_C");

}

