#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TcpSocketPlugin

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class TcpSocketPlugin.TcpSocket
// 0x0028 (0x0050 - 0x0028)
class UTcpSocket final : public UObject
{
public:
	uint8                                         Pad_1B61[0x28];                                    // 0x0028(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TcpSocket">();
	}
	static class UTcpSocket* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTcpSocket>();
	}
};
static_assert(alignof(UTcpSocket) == 0x000008, "Wrong alignment on UTcpSocket");
static_assert(sizeof(UTcpSocket) == 0x000050, "Wrong size on UTcpSocket");

// Class TcpSocketPlugin.TcpSocketSettings
// 0x0008 (0x0030 - 0x0028)
class UTcpSocketSettings final : public UObject
{
public:
	bool                                          bPostErrorsToMessageLog;                           // 0x0028(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1B62[0x7];                                     // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TcpSocketSettings">();
	}
	static class UTcpSocketSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTcpSocketSettings>();
	}
};
static_assert(alignof(UTcpSocketSettings) == 0x000008, "Wrong alignment on UTcpSocketSettings");
static_assert(sizeof(UTcpSocketSettings) == 0x000030, "Wrong size on UTcpSocketSettings");
static_assert(offsetof(UTcpSocketSettings, bPostErrorsToMessageLog) == 0x000028, "Member 'UTcpSocketSettings::bPostErrorsToMessageLog' has a wrong offset!");

}

