#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ClassAndRankIcon_S

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DungeonCrawler_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_ClassAndRankIcon_S.WB_ClassAndRankIcon_S_C
// 0x0018 (0x0370 - 0x0358)
class UWB_ClassAndRankIcon_S_C final : public UClassRankIconBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ClassIcon_S;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_RankIcon_S_C*                       WB_RankIcon_S;                                     // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetRankGroupData(const class UDCLeaderboardRankGroupDataAsset* InLeaderboardRankGroupData);
	void SetRankData(const class UDCLeaderboardRankDataAsset* InLeaderboardRankData);
	void SetClassIcon(const class UTexture2D* InClassIconTex);
	void ExecuteUbergraph_WB_ClassAndRankIcon_S(int32 EntryPoint);
	void ClearRankData();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_ClassAndRankIcon_S_C">();
	}
	static class UWB_ClassAndRankIcon_S_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_ClassAndRankIcon_S_C>();
	}
};
static_assert(alignof(UWB_ClassAndRankIcon_S_C) == 0x000008, "Wrong alignment on UWB_ClassAndRankIcon_S_C");
static_assert(sizeof(UWB_ClassAndRankIcon_S_C) == 0x000370, "Wrong size on UWB_ClassAndRankIcon_S_C");
static_assert(offsetof(UWB_ClassAndRankIcon_S_C, UberGraphFrame) == 0x000358, "Member 'UWB_ClassAndRankIcon_S_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_ClassAndRankIcon_S_C, ClassIcon_S) == 0x000360, "Member 'UWB_ClassAndRankIcon_S_C::ClassIcon_S' has a wrong offset!");
static_assert(offsetof(UWB_ClassAndRankIcon_S_C, WB_RankIcon_S) == 0x000368, "Member 'UWB_ClassAndRankIcon_S_C::WB_RankIcon_S' has a wrong offset!");

}

