#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CharacterCreate_ClassAttributeItem

#include "Basic.hpp"

#include "WB_CharacterCreate_ClassAttributeItem_classes.hpp"
#include "WB_CharacterCreate_ClassAttributeItem_parameters.hpp"


namespace SDK
{

// Function WB_CharacterCreate_ClassAttributeItem.WB_CharacterCreate_ClassAttributeItem_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWB_CharacterCreate_ClassAttributeItem_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_CharacterCreate_ClassAttributeItem_C", "OnListItemObjectSet");

	Params::WB_CharacterCreate_ClassAttributeItem_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_CharacterCreate_ClassAttributeItem.WB_CharacterCreate_ClassAttributeItem_C.ExecuteUbergraph_WB_CharacterCreate_ClassAttributeItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_CharacterCreate_ClassAttributeItem_C::ExecuteUbergraph_WB_CharacterCreate_ClassAttributeItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_CharacterCreate_ClassAttributeItem_C", "ExecuteUbergraph_WB_CharacterCreate_ClassAttributeItem");

	Params::WB_CharacterCreate_ClassAttributeItem_C_ExecuteUbergraph_WB_CharacterCreate_ClassAttributeItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

